### ISSUE TITLE
GetKey is really strict

### ISSUE THREAD

**Issue by jnardone** [SteveSyfuhs/Kerberos.NET#10]
I am debugging a program trying to use this assembly.

`KeyTable.GetKey` seems really strict for what's trying to happen here.

I can understand the strict match on `EncryptionType` + `PrincipalName`, though using `PrincipalName.Equals` for this might be a bit too strict.  `Equals` is built to exactly match, which is correct for `Equals`, but for finding a match, shouldn't this allow for a keytab that has more than one Name for a given Principal and EncryptionType?  You can have more than one SPN for an account, but obviously an incoming request is only going to have a single SPN.  (Also: it's not clear to me that a NameType mismatch is truly a mismatch, e.g. `NT_PRINCIPAL` in the keytab and `NT_SRV_INST` in the request.  Other libraries are more forgiving in this area.)

Next... if that matching fails (in `KeyTable.GetKey`) it will use the first entry, but **only** if there's only a single entry in the keytab.  But shouldn't this take the first entry **for the given EncryptionType**?  If I have 5 entries in my keytab, for the 5 different supported algorithms, and my incoming request says RC4_HMAC_NT, if I don't get a match based on type+name, why wouldn't we pick the first RC4_HMAC_NT in the keytab?

**Comment by jnardone** [comment]
That's fair.  I'll ponder this a bit and see if I can work something up...  Thanks for the response!

**Comment by SteveSyfuhs** [comment]
This can be closed thanks to your PR. :) It's been uploaded to Nuget. Mind the version indexing. It should be available here at some point: https://www.nuget.org/packages/Kerberos.NET/2.1.222.1
