### ISSUE TITLE
[question] Getting ticket details after authentication?

### ISSUE THREAD

**Issue by jnardone** [SteveSyfuhs/Kerberos.NET#12]
Is there a way to properly extract details about the incoming ticket after I've authenticated it?

The validator returns a bunch of interesting information, notably in the ticket (like the various timestamps and the ticket flags) but I can't figure out how to get at that information.  Using the validator outside of `.Authenticate` triggers the replay detection logic, in either direction since the authentication call is doing it's own `.Validate`.

Am I missing something obvious of how to get at the validated/decrypted token inside of the `KerberosAuthenticator`?

**Comment by SteveSyfuhs** [comment]
What you can do is override a few methods in the authenticator. For instance:

```
protected virtual ClaimsIdentity ConvertTicket(DecryptedData data)
{
	var ticket = data.Ticket;

	var claims = new List<Claim>();

	foreach (var authz in ticket.AuthorizationData.Authorizations)
	{
		if (authz.PrivilegedAttributeCertificate != null)
		{
			MergeAttributes(ticket, authz.PrivilegedAttributeCertificate, claims);
		}
	}

	return new ClaimsIdentity(claims, "Kerberos", ClaimTypes.NameIdentifier, ClaimTypes.Role);
}
```
Easiest approach is to just stuff the identity with more claims based on e.g. whatever is in DecryptedData.

**Comment by SteveSyfuhs** [comment]
… and that would end up looking something like...

```
public class MyAuthenticator : KerberosAuthenticator
{

	public MyAuthenticator(KeyTable keytab)

		: base(keytab)

	{ }

	protected override ClaimsIdentity ConvertTicket(DecryptedData data)
	{
		var identity = base.ConvertTicket(data);
		
		// ... add or remove claims from data
		
		return identity;
	}
}
```
