### ISSUE TITLE
Null reference exception on Authenticate

### ISSUE THREAD

**Issue by gislikonrad** [SteveSyfuhs/Kerberos.NET#13]
When calling KerberosAuthenticator.Authenticate a null reference exception is thrown. 

I dug down into the code and it seems to happen when adding the Sid claim because the pac.LoginInfo is null.

Digging deeper, it seems the NdrBinaryReader can't read non ascii characters.

**Comment by gislikonrad** [comment]
Yeah, it was UserDisplayName on line 122 of PacLogonInfo

**Comment by gislikonrad** [comment]
The underlying exception that gets swallowed is explained in this [msdn post](https://social.msdn.microsoft.com/Forums/en-US/98cd0f12-cb71-48bf-8475-157547bcb6e9/binary-reader-error-reading-char?forum=csharplanguage).

**Comment by SteveSyfuhs** [comment]
Well thats...dumb. I can look into this tonight. Any chance you can provide that byte array of the PAC as base64 or whatever? No worries if you can't. I just would need to get the right Unicode sample case.

**Comment by gislikonrad** [comment]
I wish I could, but I can't... Sorry. If the solution hasn't been found by the morning, I'll see what I can do.

**Comment by SteveSyfuhs** [comment]
No worries. I know what the solution is, just annoying to test since I need to generate a PAC with unicode.

**Comment by SteveSyfuhs** [comment]
So I think this will fix it if you want to give it a try. I'll test it properly, but I've got to spin up a new DC and that's going to take an hour.

The gist of the change is to not rely on binary reader to interpret the char size and just read the whole thing and let Encoding figure it out instead.

```
public string ReadString(int maxLength = int.MaxValue)
{
    var total = ReadInt() * 2;
    var unused = ReadInt() * 2;
    var used = ReadInt() * 2;

    if (maxLength < total)
    {
        throw new InvalidDataException($"Max length of string {maxLength} is greater than total length {total}");
    }

    if (unused > total || used > total - unused)
    {
        throw new InvalidDataException(
            $"ReadString failed with weird results. Total: {total}; Unused: {unused}; Used: {used}"
        );
    }

    reader.BaseStream.Seek(unused, SeekOrigin.Current);

    var chars = new byte[used];

    for (var l = 0; l < used; l++)
    {
        chars[l] = reader.ReadByte();
    }

    var readTo = chars.Length;

    if (readTo > 1 &&
        chars[chars.Length - 1] == '\0' &&
        chars[chars.Length - 2] == '\0')
    {
        readTo -= 2;
    }

    return Encoding.Unicode.GetString(chars, 0, readTo);
}
```

**Comment by SteveSyfuhs** [comment]
Okay, so it looks like that did indeed fix it. Check the screenshot. The display name is "admin 0x00ED0x21220x00ED0x21220x00ED0x2122"

![unicode](https://user-images.githubusercontent.com/1210849/39285510-9924e02a-48cd-11e8-95eb-1b603dc094dc.png)

**Comment by SteveSyfuhs** [comment]
And just to follow up. This has been pushed to nuget as https://www.nuget.org/packages/Kerberos.NET/2.1.426.1

**Comment by gislikonrad** [comment]
That's fantastic. It works.
