### ISSUE TITLE
Exception creating an instance of KerberosValidator on .NET Core 2.0

### ISSUE THREAD

**Issue by dave-wharton** [SteveSyfuhs/Kerberos.NET#14]
When creating an instance of the KerberosValidator were are getting the following exception:
_Method 'GetAsync' in type 'Kerberos.NET.DistributedMemoryCache' from assembly 'Kerberos.NET, Version=2.0.0.0, Culture=neutral, PublicKeyToken=10b231fbfc8c4b4d' does not have an implementation._

`var validator = new KerberosValidator(new KerberosKey(Options.Secret)) { ValidateAfterDecrypt = ValidationActions.All };`

Is there something I need to do to avoid this exception?

**Comment by SteveSyfuhs** [comment]
It's been a while and I can't remember exactly why this happens, but I think you can work around it by adding a nuget package reference directly to "Microsoft.Extensions.Caching.Memory".

**Comment by dave-wharton** [comment]
Thanks for the quick reply. I tried adding the nuget package "Microsoft.Extensions.Caching.Memory" reference directly to my project that creates the KerberosValidator, but the exception is still thrown.

Any other ideas? Thanks!

**Comment by SteveSyfuhs** [comment]
That's a bit surprising then. Let me give it a try and see if I can reproduce this. What runtime are you trying this against?

**Comment by dave-wharton** [comment]
We are using .NET Core 2.0. Let me know require anything further.

**Comment by SteveSyfuhs** [comment]
I can't seem to reproduce this. I suspect what might be happening is that there's a dependency getting loaded from another library (maybe?) that uses a different version of the interface. I'm just going to rip this out so it doesn't have any dependencies and replace with it's own dedicated interface. Expect an update some time later tonight.

**Comment by SteveSyfuhs** [comment]
Okay, so this has been resolved for good. I ripped out the different cache bits and merged it into a single thing. It's available as the latest nuget package 2.2.512.1.

**Comment by dave-wharton** [comment]
That worked! Thanks very much.

**Comment by SteveSyfuhs** [comment]
😁
