### ISSUE TITLE
Update CI to build on commits to master / PRs

### ISSUE THREAD

**Issue by gfoidl** [SteveSyfuhs/Kerberos.NET#143]
It looks like [CI](https://syfuhs2.visualstudio.com/Kerberos.NET/_build) doesn't run on commits to _master_ or for _PR_.
At least the badge in _ReadMe_ points to a different (previous) config of CI.

Edit: sorry for the label (can't remove it). It's from the issue-template.

**Comment by SteveSyfuhs** [comment]
Nice catch. This must have failed when we migrated the repo to /dotnet. I'll take a look today.

________________________________

**Comment by SteveSyfuhs** [comment]
The build has been migrated to use the dotnet/ repo now.
