### ISSUE TITLE
S4U AP_REQ error

### ISSUE THREAD

**Issue by dev-2null** [SteveSyfuhs/Kerberos.NET#149]
Not sure if I implement it correctly, but I got  `'KDC KRB_AP_ERR_MODIFIED: Message stream modified'` after setting `s4u`.

```cs
string s4u = "user@domain.local";
 var rst = new RequestServiceTicket()
            {
                ServicePrincipalName = spn,
                ApOptions = apOptions,
                S4uTarget = s4u,
                S4uTicket = s4uTicket,
                UserToUserTicket = u2uServerTicket,
                KdcOptions = kdcOptions,
                Realm = domainName,
            };
```
I'm trying to get a TGT for serviceA and then utilize S4U extension to get a service ticket on behalf a normal user to this serviceA.

Could you please check it?
Thanks!

**Comment by SteveSyfuhs** [comment]
Die you get it working?

________________________________

**Comment by dev-2null** [comment]
Hey yes, it's my mistake... But another stupid question: Is there any support for LSA interaction? `klist` cannot see any resulting tickets...

**Comment by SteveSyfuhs** [comment]
No, it's completely independent from the Windows implementation.

________________________________
