### ISSUE TITLE
.NET Core application - unmanaged calls to DllImport("ntdll.dll") fails on Linux

### ISSUE THREAD

**Issue by dave-wharton** [SteveSyfuhs/Kerberos.NET#15]
This works fine on Windows, but fails on Linux which makes sense as the DLL is not present. Is there anyway to support the compressions that rely on the unmanage calls when running on a non-windows platform?

We are running under docker containers which is why we have run into this issue.

**Comment by SteveSyfuhs** [comment]
Does it kill the entire processing of the ticket, or just the decompress stage? It should only fail decompression and carry on without. If it kills the entire thing then that's a bug.

It's possible to get the decompress to work on Linux, but it requires building/finding the right algorithm, and it's not a standard deflate.

The possible options are:

 * COMPRESSION_FORMAT_NONE:  No compression. 

 * COMPRESSION_FORMAT_LZNT1:  The LZNT1 compression algorithm is used. For more information, see [MS-XCA] section 2.5. 

 * COMPRESSION_FORMAT_XPRESS:  The Xpress LZ77 compression algorithm is used. For more information, see [MS-XCA] sections 2.3 and 2.4. 

 * COMPRESSION_FORMAT_XPRESS_HUFF:  The Xpress LZ77+Huffman compression algorithm is used. For more information, see [MS-XCA] sections 2.1 and 2.2.

**Comment by SteveSyfuhs** [comment]
Cool. This only affects claims, if they happen to be present. In all likelihood, it's probably an empty claims array anyway.
