### ISSUE TITLE
Submit ticket to LSA

### ISSUE THREAD

**Issue by dev-2null** [SteveSyfuhs/Kerberos.NET#150]
**Is your feature request related to a problem? Please describe.**
A console app does not have tickets left in memory for further use. E.g. If I obtain a service ticket for CIFS via a console app, I should be able to do `dir \\target\share` after running the app...

**Describe the solution you'd like**
Use `LsaCallAuthenticationPackage()` with a message type of `KERB_SUBMIT_TKT_REQUEST` to submit a ticket for the current (or specified) logon session? I'm really bad at coding....

**Comment by SteveSyfuhs** [comment]
Why would you want to use this library and then push the tickets into LSA? Why wouldn't you just use the built-in Kerberos library in Windows to do the same thing?

It's certainly possible to stick the ticket into LSA though (but it can't be pulled back out).

**Comment by dev-2null** [comment]
Hi, .NET is preferable for me. I just reused some other code from Github to achieve it. Thx!
