### ISSUE TITLE
can you validate implicitly vs. keytab?

### ISSUE THREAD

**Issue by jnardone** [SteveSyfuhs/Kerberos.NET#16]
Is there a way to use this library on a domain-connected machine to validate tokens, but without having to use a manual keytab file(and instead use the existing domain membership of the computer in question as the connection back to the directory)?

**Comment by SteveSyfuhs** [comment]
In a manner of speaking, yes. You have to extract the machine password. This requires admin (or system) rights, and you need to set a registry flag to get a decrypted version of the password. This is the worst case security scenario, so it's not recommended for any production systems. At that point you're better off just handing it off to `AcceptSecurityContext` to get the identity.

That said, the gist of how it works can be found here: https://github.com/SteveSyfuhs/Kerberos.NET/blob/master/KerbDump/Form1.cs#L114

I have not documented the registry key you need to set, but it can be found online.

**Comment by jnardone** [comment]
oh, true.  so i'd need a handle (from AcquireCredentialsHandle) (with the principal set to the expected SPN?) and then pass in the raw credential to AcceptSecurityContext? The workflow here on the windows/sspi side is.. not the most intuitive thing.

**Comment by SteveSyfuhs** [comment]
Yes, that's how it works. Instead of doing all this manually, a slightly saner approach might be to use a library like:

 * https://github.com/antiduh/nsspi
 * https://github.com/Waffle/waffle

**Comment by jnardone** [comment]
Yes, i've been digging into nsspi but for some reason my spnego kerberos tickets are returning a CONTINUE from AcceptSecurityContext even though the same ticket validates correctly with no further input through your excellent lib.

**Comment by jnardone** [comment]
Even with a SPNEGO/kerberos ticket?  That would do it.  I wonder if I can tell nsspi whether to just ignore that part...

**Comment by SteveSyfuhs** [comment]
SPNEGO is just a wrapped Kerb ticket in this scenario. AFAIK you can't do that from the server side. The client requests it when it calls `InitializeSecurityContext` with the ISC_MUTUAL_AUTH flag.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa374770(v=vs.85).aspx

**Comment by jnardone** [comment]
Sorry, I meant ignore that required response and still get at the authenticated user session info.  All this to try and avoid having to make customers generate a keytab but still be able to proxy validate the token. 

Essentially, what I'm trying to do is

browser <-> webserver <-> remote API server <-> domain server

browser<->WS is doing the SPNEGO/kerb exchange, i'm extracting the token and then ferrying that offto a remote server that can talk to the domain.  Remote API server is IIS/.NET so trying to avoid keytab.

But of course that browser request is going to have the SPN of HTTP/webserver, so I know I need that SPN added to the DC, but was hoping at the API server I could just say "this token is meant for HTTP/webserver even though you are HTTP/apiserver" and leverage the SSPI stuff to piggyback on the fact that the API server is joined to the domain already...

**Comment by jnardone** [comment]
So trying to make sure I understand this.  (Though perhaps I'm just trying to square peg/round hole this too much...)   To be able to essentially proxy the auth check (the webserver has no direct linkage to the domain, either domain membership or even access to the necessary ports; I just want to pass the existing encoded token along for a "who is this, and is it valid?" check) I'd need the same underlying password for the account associated with the WS SPN as well as the validation API service SPN?

I'm trying to do
Browser -> WS -> Validation API Service (which can talk to DC)

1. I will have to have an SPN for the hostname of the web server
2. The SPN of the validation API service will definitely be different
3. That SPN has to be associated with a user acct
4. The Validation service (running on a DC as part of IIS, but NOT using the built-in windows auth stuff) will have an SPN as well.

If the passwords to both accounts associated with the SPN are the same, the validation *should* be successful.

But this seems wonky, when I can go and create the SPN for the webserver and use the kerberos.net stuff with that keytab for my SPN and not worry about lining up the passwords etc.  

Yes?  (i wouldn't blame you if I'm completely lost you, I'm not entirely sure where I am myself!)

**Comment by jnardone** [comment]
...but I'm not sure I can get around this -> 

> That's because the ticket sent by the client has the Mutual Auth flag set. This tells the server to return an authenticatable piece of data back to the client to prove it's really the right server, and then the client sends a final 'ok' to the server, which is used to generate the identity.

**Comment by jnardone** [comment]
Anyway, this is not a Kerberos.NET problem (K.N actually gives me an enablement path that doesn't require that last handshake) so I'm going to close this.
