### ISSUE TITLE
Use MIT cache file for ticket management

### ISSUE THREAD

**Issue by mikeTWC1984** [SteveSyfuhs/Kerberos.NET#160]
Qustion - is it possible to add Kerberos.Net generated ticket to MIT kerberos cache file (basically mirror what kinit does) or create a separate cache file that can be consumed by MIT kerberos?

**Comment by SteveSyfuhs** [comment]
There isn't a native serializer for the cache format, but it's certainly possible to wire one in if you know the MIT format. You can create a custom ITicketCache and set it on the client. Then any calls to get the tickets will be stored in the file.

________________________________

**Comment by SteveSyfuhs** [comment]
The feature has been added by #176. It can be used by setting the client cache to a new instance of a `Krb5TicketCache`.

```csharp
var client = new KerberosClient(loggerFactory) { Cache = new Krb5TicketCache(pathToKrb5ccFile, loggerFactory) }
```
