### ISSUE TITLE
Signed PAC: KRB_AP_ERR_MODIFIED

### ISSUE THREAD

**Issue by dev-2null** [SteveSyfuhs/Kerberos.NET#161]
Hi,
I got `KRB_AP_ERR_MODIFIED  Message stream modified` after signing a new PAC with krbtgt key. Is that an expected behavior? What need to be in the PAC? It behaves normally if I don't include a PAC in the ticket.

```cs
var pac = new PrivilegedAttributeCertificate(){ };
pac.Encode(krbtgtKey, krbtgtKey);
```
Thanks!

**Comment by SteveSyfuhs** [comment]
This should work. For what service though?

It's supposed to be signed by the krbtgt and target service account key.

________________________________

**Comment by dev-2null** [comment]
For TGT, both kdcSig and serverSig should be signed by the krbtgt key

**Comment by SteveSyfuhs** [comment]
Ah. A real DC is returning that error? It will most likely need a bunch of stuff in logoninfo otherwise it's genuinely an invalid PAC.

________________________________

**Comment by dev-2null** [comment]
Yes. Shouldn't it work if it is an empty PAC? the server will verify the checksum and it should be validated if the data does not changed?  
It returns the same error even thought I construct the logoninfo manually

**Comment by SteveSyfuhs** [comment]
🤷‍♂️ It's difficult to say what it expects without sticking a debugger on a DC. A PAC is a complicated structure and it's not well documented what's explicitly required.

________________________________

**Comment by dev-2null** [comment]
Yeah. Thanks though

**Comment by dev-2null** [comment]
I still get the same error after reusing the PAC from the same user.

```cs
var ticketDecrypted = asRep.Ticket.EncryptedPart.Decrypt(krbtgtKey, KeyUsage.Ticket,b => KrbEncTicketPart.DecodeApplication(b));
PrivilegedAttributeCertificate pac = null;
foreach (var data in ticketDecrypted.AuthorizationData)
{
    if (data.Type == AuthorizationDataType.AdIfRelevant)
    {
        var decodedData = data.DecodeAdIfRelevant();
        foreach (var data2 in decodedData)
        {
            if (data2.Type == AuthorizationDataType.AdWin2kPac)
            {
                pac = new PrivilegedAttributeCertificate(data2);
            }
        }
    }
}
pac.KdcSignature = null;
pac.ServerSignature = null;
pac.Encode(kerbCred.CreateKey(), kerbCred.CreateKey());
```
Any thoughts?

**Comment by SteveSyfuhs** [comment]
Sounds to me like a bug in the encode process. I'll have to debug it a bit. I can take a look in the morning.

To repro it are you grabbing a ticket, decoding, re-encoding, and then making a new request to a DC?

________________________________

**Comment by dev-2null** [comment]
Yes, I grab the PAC from a decoded TGT, then sign the PAC again, re-assemble the PAC into a new TGT(has the same properties), and make TGS request. Thanks!

============================================
Expected PAC value using the krbtgtKey (`pac.Encode(krbtgtKey, krbtgtKey)`)

`KDC Signature/Checksum != Server Signature/Checksum`

Signing with the same krbtgt key results in the same sig/checksum:

`KDC Signature/Checksum == Server Signature/Checksum`

**Comment by dev-2null** [comment]
FYI: [MS-KILE] Section 3.3.5.6.4.3 and 3.3.5.6.4.4
**Server Signature:**
`The Signature field is the keyed hash ([RFC4757]) of the entire PAC message with the Signature fields of both PAC_SIGNATURE_DATA structures set to zero.`
**KDC Signature:**
`The Signature field is the keyed hash ([RFC4757]) of the Server Signature field in the PAC message.`

**Comment by SteveSyfuhs** [comment]
I was able to reproduce your setup. My code authenticates, extracts the krbtgt and decrypts, re-encrypts, re-encodes, caches, and requests a new service ticket. This on its own works fine. I'm going to see about modifying the PAC.

However before I do that I noticed something: the signatures for the KDC and Server fields are different, meaning the server key isn't the same as the KDC key. I have no idea what key is being used here. I'll have to do a bit of digging.

**Comment by dev-2null** [comment]
Yeah, I noticed that. But I think the key is the same one. 
Maybe check the book:[ Network Security Assessment Table 7-26  ](https://books.google.de/books?id=fpSpDQAAQBAJ&pg=PA192&lpg=PA192&dq=Network+Security+Assessment+Table+7-26&source=bl&ots=DZnKhlVsoz&sig=ACfU3U0fMjV4MOxAeJPui6xlSF0MxbbWuQ&hl=en&sa=X&ved=2ahUKEwjrr4bp8qzpAhUExYUKHXDXDw8Q6AEwAHoECAgQAQ#v=onepage&q=Network%20Security%20Assessment%20Table%207-26&f=false)

Also kerberos implementation of mimikatz: https://github.com/gentilkiwi/mimikatz/blob/master/mimikatz/modules/kerberos/kuhl_m_kerberos.c#L430

**Comment by SteveSyfuhs** [comment]
I could also just look at the AD source...

**Comment by SteveSyfuhs** [comment]
The issue is the KDC signature is a hash over the server signature. The keys are the same. Lemme see what a proper fix would look like.

**Comment by dev-2null** [comment]
Great! Looking forward to that

**Comment by SteveSyfuhs** [comment]
PR is out https://github.com/dotnet/Kerberos.NET/pull/163

**Comment by dev-2null** [comment]
Thanks for the quick fix! A stupid question: How do I apply the update into my project (create a nuget?)

**Comment by dev-2null** [comment]
I Pack the project by myself and install the NuGet offline, but I got another exception:
```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: str
   at System.Security.Cryptography.Asn1.AsnWriter.WriteCharacterString(UniversalTagNumber encodingType, String str)
   at Kerberos.NET.Entities.KrbKdcReqBody.Encode(AsnWriter writer, Asn1Tag tag)
   at Kerberos.NET.Entities.KrbKdcReqBody.Encode(AsnWriter writer)
   at Kerberos.NET.Entities.KrbKdcReq.Encode(AsnWriter writer, Asn1Tag tag)
   at Kerberos.NET.Entities.KrbKdcReq.EncodeApplication(AsnWriter writer, Asn1Tag tag)
   at Kerberos.NET.Entities.KrbKdcReq.EncodeApplication(Asn1Tag tag)
   at Kerberos.NET.Entities.KrbAsReq.EncodeApplication()
```
Any idea? It works fine with the previous NuGet package

**Comment by dev-2null** [comment]
Thanks for the quick fix, I still have some problems with my code, but re-encoding the PAC works now, Let me check if there's any problem with it

**Comment by dev-2null** [comment]
I'm still getting the modified error. I found the problem:

I created a new class in my code:
```cs
        public class PacClientInfo2 : PacClientInfo
        {
            [KerberosIgnore]
            public new short NameLength { get;  set; }
            public override void Unmarshal(ReadOnlyMemory<byte> bytes)
            {
                var buffer = new NdrBuffer(bytes);
                ClientId = buffer.ReadStruct<RpcFileTime>();
                //NameLength = buffer.ReadInt16LittleEndian();
                if (NameLength > 0)
                {
                    Name = buffer.ReadFixedPrimitiveArray<char>(NameLength / sizeof(char)).ToString();
                }
            }
        }
```
And constuct this ClientInfo with
```cs
var clientInformation = new PacClientInfo2()
            {
                Name = username,
                ClientId = RpcFileTime.Convert(DateTime.Now),
                NameLength = (short)(username.Length * 2)
            };
```
Any idea to construct the clientInfo manully? Thanks!

**Comment by SteveSyfuhs** [comment]
Something gets corrupted when you modify the PAC directly. I have to dig into it, but it's a low priority because this isn't a normal use case. You can rebuild the entire authz bits and it should work fine. The above PacClientInfo2 fix shouldn't be necessary at all.

```csharp
var pacStr = ticket.AuthorizationData.FirstOrDefault(f => f.Type == AuthorizationDataType.AdIfRelevant)
									 .DecodeAdIfRelevant()
									 .FirstOrDefault(f => f.Type == AuthorizationDataType.AdWin2kPac);

var pac = new PrivilegedAttributeCertificate(pacStr);

ticket.AuthorizationData = new[]
{
	new KrbAuthorizationData
	{
		Type = AuthorizationDataType.AdIfRelevant,
		Data = new KrbAuthorizationDataSequence
		{
			AuthorizationData = new[]
			{
				new KrbAuthorizationData
				{
					Type = AuthorizationDataType.AdWin2kPac,
					Data = pac.Encode(kerbKey, kerbKey)
				}
			}
		}.Encode()
	}
};
```

**Comment by dev-2null** [comment]
But with the default clientInfo class, there's no way to specify the NameLength:

```cs
var clientInformation = new PacClientInfo()
            {
                Name = username,
                ClientId = RpcFileTime.Convert(DateTime.Now),
            };
``` 
This will result in a zero name length. I wanted to replace this ClientInformation part in a normal PAC.
I always get this error:
```
Unhandled Exception: System.ArgumentException: Offset 16 greater than buffer length 0
Parameter name: offset
   at Kerberos.NET.Ndr.NdrBuffer.MoveByOffset(Int32 offset)
   at Kerberos.NET.Ndr.NdrBuffer.ReadMemory(Int32 length)
   at Kerberos.NET.Ndr.NdrBuffer.Read(Int32 length)
   at Kerberos.NET.Ndr.NdrBuffer.ReadFixedPrimitiveArray[T](Int32 knownLength)
   at Kerberos.NET.Entities.PacClientInfo.Unmarshal(ReadOnlyMemory`1 bytes)
   at Kerberos.NET.Entities.PrivilegedAttributeCertificate.ParsePacType(PacType type, ReadOnlyMemory`1 pacInfoBuffer, Int32& exclusionStart, Int32& exclusionLength)
   at Kerberos.NET.Entities.PrivilegedAttributeCertificate..ctor(KrbAuthorizationData authz)
```

**Comment by dev-2null** [comment]
Probably I didn't explain it very clear. Basically I reused the same PAC, but only replace the ClientInformation part. Everything works fine until I use my own clientinfo. 
`Kerberos Error: KDC KRB_ERR_GENERIC: Generic error`

**Comment by SteveSyfuhs** [comment]
My mistake, I was reading it wrong. Updating the PR.

**Comment by SteveSyfuhs** [comment]
The PR has been updated with the fix.

**Comment by dev-2null** [comment]
```cs
var clientInformation = new PacClientInfo2()
{
    Name = username,
    ClientId = RpcFileTime.Convert(DateTime.Now),
};
pac.ClinetInformation = clientInformation;
```

```
Unhandled Exception: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
```
Is just my error or there are other consequences of the fix?

**Comment by dev-2null** [comment]
Got some other issues...will let you know once I figure it out

**Comment by dev-2null** [comment]
With the previous code (replace the normal PAC's ClientInformaiton with a new one), I'm getting `KDC KRB_AP_ERR_MODIFIED: Message stream modified`

**Comment by dev-2null** [comment]
Thank you very much! Problem solved.
