### ISSUE TITLE
Authentication with RID 500 admin

### ISSUE THREAD

**Issue by dev-2null** [SteveSyfuhs/Kerberos.NET#164]
The default `client.Authenticate(cred)` works fine for all domain accounts, but if you step through the authenticate process in the Authenticate() Task, you will get `KDC KDC_ERR_PREAUTH_FAILED: Pre-authentication information was invalid` for RID 500 built-in domain\administrator account. All the other domain accounts work perfectly. Could you please help to check if there's anything wrong?
```cs
var client = new Kerberos.NET.Client.KerberosClient();
var kerbCred = new Kerberos.NET.Credentials.KerberosPasswordCredential(user, pass, domain);
var auo = AuthenticationOptions.RepPartCompatible |
    AuthenticationOptions.IncludePacRequest |
    AuthenticationOptions.RenewableOk |
    AuthenticationOptions.Canonicalize |
    AuthenticationOptions.Renewable |
    AuthenticationOptions.Forwardable |
    AuthenticationOptions.PreAuthenticate;
var asReqMessage = KrbAsReq.CreateAsReq(kerbCred, auo);
var asReq = asReqMessage.EncodeApplication();
var test = await transport.SendMessage<KrbAsRep>(kerbCred.Domain, asReq);
```
Thanks!

**Comment by SteveSyfuhs** [comment]
Are you saying all accounts work for `Authenticate` EXCEPT the DA 500? Or all accounts except DA 500 work when you call the transport directly? 

This works for me:

```csharp
var client = new KerberosClient();

var credential = new KerberosPasswordCredential("administrator", "P@ssw0rd!", "corp.identityintervention.com");

await client.Authenticate(credential);
```

My guess is the salt that's getting generated by `KerberosPasswordCredential` is wrong. The Client itself handles this logic by sending a request for pre-auth without any PA timestamp where the KDC returns an error message including the appropriate salts. Since you're using the transport directly this logic doesn't exist and the credential itself must guess at what salt to use. In this case it's probably guessing wrong. Not much can be done about it, you either guess right or you don't. You can supplement that by appending the salts to the credential with `kerbCred.Salts` though at that point I would recommend just using the client.

The built-in domain admin account is special in this regard. It gets its' salt information prior to the machine being converted into a domain, so the salt algorithm it uses doesn't match the standard implementation (chicken and egg problem -- the domain doesn't exist so you can't use it to provide data for the salt). The salt for this user is OriginalDCHostName|UserName. In my test domain that is `WIN-RFTG0BD1S70Administrator` .

**Comment by dev-2null** [comment]
Thanks for the answer, and Yes I mean all accounts except DA 500 work when I call the transport directly, specifically what's in the `RequestTGT()` method.
From what I have observed, the DA 500 user has the same salt structure with other domain users. (The krb error message returns `DOMAIN.LOCALAdministrator`). Also if you issue the `runas` command to run as the DA 500 user, you will see the same salt that returned by the DC.

**Comment by SteveSyfuhs** [comment]
The password has probably been changed. That salt only applies to the first password created.

In either case it's the same basic issue. The key is attempting to use is the wrong salt. That's why the client always tries to get the salt first. This is not guaranteed to work without knowing for a fact what the salt is.

**Comment by dev-2null** [comment]
Should it work in such salt structure (DOMAINUser) for 500 admin account? I reckon all user should be able to authenticate successfully if KDC returns the same salt structure.

**Comment by SteveSyfuhs** [comment]
Assuming the actual salt it guesses matches then it should work. It just needs salt and password to match for the crypto to work.

If you can, take a peek at the internals of the KerberosKey.Salt property for the user. This is where it's attempting to guess the salt. The stack would look something like this:

```
Kerberos.NET.dll!Kerberos.NET.Crypto.AES.AesSalts.GenerateSalt(Kerberos.NET.Crypto.KerberosKey key)
Kerberos.NET.dll!Kerberos.NET.Crypto.AES.AESTransformer.String2Key(Kerberos.NET.Crypto.KerberosKey key)
Kerberos.NET.dll!Kerberos.NET.Crypto.KerberosKey.GetKey(Kerberos.NET.Crypto.KerberosCryptoTransformer transformer)
Kerberos.NET.dll!Kerberos.NET.Crypto.KerberosKey.GetOrDeriveKey.AnonymousMethod__0(string str)
System.Collections.Concurrent.dll!System.Collections.Concurrent.ConcurrentDictionary<string, System.ReadOnlyMemory<byte>>.GetOrAdd(string key, System.Func<string, System.ReadOnlyMemory<byte>> valueFactory)
Kerberos.NET.dll!Kerberos.NET.Crypto.KerberosKey.GetOrDeriveKey(Kerberos.NET.Crypto.KerberosCryptoTransformer transformer, string cacheKey, System.Func<System.ReadOnlyMemory<byte>, System.ReadOnlyMemory<byte>> dk)
Kerberos.NET.dll!Kerberos.NET.Crypto.AES.AESTransformer.GetOrDeriveKey(Kerberos.NET.Crypto.KerberosKey kerberosKey, Kerberos.NET.Crypto.KeyUsage usage)
Kerberos.NET.dll!Kerberos.NET.Crypto.AES.AESTransformer.Encrypt(System.ReadOnlyMemory<byte> data, Kerberos.NET.Crypto.KerberosKey kerberosKey, Kerberos.NET.Crypto.KeyUsage usage)
Kerberos.NET.dll!Kerberos.NET.Entities.KrbEncryptedData.Encrypt(System.ReadOnlyMemory<byte> data, Kerberos.NET.Crypto.KerberosKey key, Kerberos.NET.Crypto.KeyUsage usage)
Kerberos.NET.dll!Kerberos.NET.Credentials.KerberosCredential.TransformKdcReq(Kerberos.NET.Entities.KrbKdcReq req)
Kerberos.NET.dll!Kerberos.NET.Entities.KrbAsReq.CreateAsReq(Kerberos.NET.Credentials.KerberosCredential credential, Kerberos.NET.Client.AuthenticationOptions options)
ConsoleApp1.dll!ConsoleApp1.Program.Main(string[] args)
```

The only variable in this case is the salt itself.

The other thing worth checking I suppose is that it's not somehow attempting to use RC4. 500 admin is in protected users which blocks RC4 use.

**Comment by dev-2null** [comment]
Good point.  Thx a lot. Will check and get back to you soon

**Comment by dev-2null** [comment]
I still don't think this unexpected behavior is related to the salt... I checked the salt for RID 500 administrator is exactly what the KDC returns back to the client... (The salt I used for admin matches the what the KDC needs). Also for protect user groups, I was able to authenticate as users in this group. It has nothing to do with the encryption algorithm.

**Comment by SteveSyfuhs** [comment]
But it definitely works using the client authenticate method?

Let me see if I can repro the scenario better where salt matches.

________________________________

**Comment by dev-2null** [comment]
Do you have any updates? I still couldn't figure out what's wrong... 
BTW, I want to ask what I should do with the license cuz I made a small tool based on your library and want to make it public, do I need to use the same license? and what else I should do? Thank you!

**Comment by SteveSyfuhs** [comment]
Sorry, just got back to it. The exact issue as _I_ have been able to reproduce it is that it's still the salt. When you change the password the salt gets updated accordingly, so the two do match. However, the difference is that the 500 account uses a capital 'A' in the sAMAccountName which changes the salt, which causes the key to derive to something else. If you capitalize the username "Administrator" or "Administrator@..." the salt is generated correctly (for me). There are two solutions to make this work:

1. Make the user enter the username verbatim to what's recorded in AD
2. Request a pre-auth error and extract the salt from that

Option 2 is documented as the correct option as per protocol spec.

For licensing, you can redistribute the code however you want, you just need to put a notice somewhere that links to https://github.com/dotnet/Kerberos.NET/blob/develop/LICENSE saying the Kerberos.NET library code itself is copyright. Any derivative work that isn't part of the library is your copyright as you see fit. For instance this library has a [NOTICES](https://github.com/dotnet/Kerberos.NET/blob/develop/NOTICES) file that does just that.

**Comment by dev-2null** [comment]
Thank you very much! Problem solved!
And really appreciate the licensing guide.
