### ISSUE TITLE
Invalid checksum

### ISSUE THREAD

**Issue by Zubastic** [SteveSyfuhs/Kerberos.NET#165]
**Describe the bug**
When keytab contains multiple version of key, for example V5 and V6. Library try to decrypt with V5 version of key and failed with Invalid checksum error.

```c#
System.Security.SecurityException: Invalid checksum
   at Kerberos.NET.Crypto.AES.AESTransformer.DecryptWith(Byte[] workBuffer, Int32[] workLens, Byte[] key, Byte[] iv, KeyUsage usage)
   at Kerberos.NET.Crypto.AES.AESTransformer.Decrypt(Byte[] cipher, Byte[] key, Byte[] iv, KeyUsage usage)
   at Kerberos.NET.Crypto.AES.AESTransformer.Decrypt(Byte[] cipher, KerberosKey key, KeyUsage usage)
   at Kerberos.NET.Crypto.DecryptedData.Decrypt(KeyTable keytab)
   at Kerberos.NET.Entities.ContextToken.Decrypt(KrbApReq token, KeyTable keytab)
   at Kerberos.NET.Entities.NegotiateContextToken.Decrypt(KeyTable keys)
   at Kerberos.NET.KerberosValidator.Validate(Byte[] requestBytes)
   at Kerberos.NET.KerberosAuthenticator.Authenticate(Byte[] token)
   at Kerberos.NET.KerberosAuthenticator.Authenticate(String token)
```

**To Reproduce**
Create keytab with multiple versions of keys and try to decrypt it.

**Expected behavior**
Success decrypt

**Additional context**
So fix is pretty simple: take only last version of keys and try to decrypt with them.

Also here a bug with sname: in keytab we have HOST entry, but KrbPrincipalName is HTTP, for example. Maybe we should implement this situation?
I created pull request with fix.

**Comment by SteveSyfuhs** [comment]
The PR looks good. Just one comment on it.

Regarding the HOST vs HTTP bit, there's a special mapping in KrbPrincipalName that will normalize the 50 or so common names that map to HOST when you call `Matches()`. You may be able to make that work.

**Comment by Zubastic** [comment]
> 
> 
> The PR looks good. Just one comment on it.
> 
> Regarding the HOST vs HTTP bit, there's a special mapping in KrbPrincipalName that will normalize the 50 or so common names that map to HOST when you call `Matches()`. You may be able to make that work.

Added to PR :)

**Comment by SteveSyfuhs** [comment]
Cool. Did you see the comment about the unit test?

**Comment by Zubastic** [comment]
> 
> 
> Cool. Did you see the comment about the unit test?

Yep, but I don't know, how to generate keytab for test.... Used for this bug keytab + token from private network and couldn't be used for tests...

**Comment by SteveSyfuhs** [comment]
Couple options I think. There's an existing test that creates keytabs: 

https://github.com/dotnet/Kerberos.NET/blob/be0901ae13a85e26d4b6ee49524b15afe5c23b0e/Tests/Tests.Kerberos.NET/Crypto/KeyTableTests.cs#L103-L125

You could modify it to add a second key with a later version and verify the retrieve gets the latest version.

**Comment by Zubastic** [comment]
> You could modify it to add a second key with a later version and verify the retrieve gets the latest version.

Tests are created.

**Comment by SteveSyfuhs** [comment]
PR has been merged.
