### ISSUE TITLE
Appears to be a bug in reading version 1 keytabs

### ISSUE THREAD

**Issue by snarfattack** [SteveSyfuhs/Kerberos.NET#17]
In KeyTable.cs, ReadPrincipal Method, `var nameType = (PrincipalNameType)ReadInt32(reader);` should not be executed if it's version 1 according to this documentation: https://web.mit.edu/kerberos/krb5-1.12/doc/formats/keytab_file_format.html

I think the code should look like:
```
var nameType = PrincipalNameType.NT_UNKNOWN;
if (version != 1)
{
    nameType = (PrincipalNameType)ReadInt32(reader);
}
```

Not that I use that version 1, nor can confirm it, but noticed this as I was doing a code review.

**Comment by SteveSyfuhs** [comment]
Certainly possible. I didn't have a v1 file to test against so didn't bother. Still don't have a file, and haven't figured out how to easily generate one, so. 🤷‍♂️

If you come across one, or an *easy* way to generate one, send it my way and I'll happily verify and fix.

**Comment by snarfattack** [comment]
As I look for more detail on if I might encounter v1 in our environment, I see that the Kerberos spec was updated to v2 of the file before even leaving beta, and we are talking mid 90's at this point. Add to that there are many vulnerabilities in that code, I'd not even worry about this. If someone is impacted by this bug, they should take that as a clue to get caught up to this century.
