### ISSUE TITLE
Missing HttpClient Example

### ISSUE THREAD

**Issue by adrianliechti** [SteveSyfuhs/Kerberos.NET#181]
Thanks to this amazing library, I easily was able to create a S4Uself and S4U2proxy ticket against a Windows AD on a Linux Machine. But now I am a little stuck to use this ticket in a HttpClient using SPNEGO.

Since you provide great samples for a Middleware, it would be great to also provide an example for a real client.

I would super appreciate if one of this community can provide my some guidance how to set the AuthenticationHeaderValue
Thanks a 1000

**Comment by SteveSyfuhs** [comment]
Try this.

```csharp
public async Task RequestWithKerberosTicket()
{
    var kerberosClient = new KerberosClient();

    await kerberosClient.Authenticate(new KerberosPasswordCredential("user@domain.com", "password"));

    var apReq = await kerberosClient.GetServiceTicket("http/foo.com");

    var bytes = apReq.EncodeGssApi();

    var headerValue = Convert.ToBase64String(bytes.ToArray());

    var httpClient = new HttpClient();

    httpClient.DefaultRequestHeaders.Authorization = new System.Net.Http.Headers.AuthenticationHeaderValue("negotiate", headerValue);

    var securedResponse = await httpClient.GetAsync("https://foo.com/secure");
   // do whatever with securedResponse
}
```

Lifetime of the KerberosClient should coincide with how long you want to keep the user ticket around. The client has various options for caching and ticket renewal strategies as well.

**Comment by adrianliechti** [comment]
OMG!
you really made my week! amazing! it works! let me buy you a beer. or five.
I cannot thank enough. also for your amazing response time!

wish you a great weekend! take care
