### ISSUE TITLE
Encryption token

### ISSUE THREAD

**Issue by samanthann** [SteveSyfuhs/Kerberos.NET#19]
In the "Using the Library" section of the ReadMe, the section line takes in a token to authenticate:
var identity = authenticator.Authenticate("YIIHCAYGKwYBBQUCoIIG...");
I also see these types of encryption tokens in the sample app "KerbTester". In the "KerberosMiddlewareEndtoEndSample" it is hard coded in the program as "NegotiateSample"

Where does this token come from? How do we generate one to use in our code if its needed? We are trying to use Kerberos to authenticate a http request, and we have a keytab but are stuck on this token. 

Thanks!

**Comment by SteveSyfuhs** [comment]
The token is generated as part of an authentication handshake between a client and server. In the case of a web app and browser, the server sends a WWW-Authenticate header and the browser will call to AD to get a token.

**Comment by samanthann** [comment]
So if the server does this, what do we pass into the Kerberos.Net library to do an HTTP call?

**Comment by SteveSyfuhs** [comment]
Nothing. Kerberos.NET is not a HTTP library. Its up to you to kick off the auth handshake in whatever protocol you're using. There are web samples that show how you would do this in the samples folder.
