### ISSUE TITLE
Authentication using CredentialCache.DefaultCredentials.

### ISSUE THREAD

**Issue by firerain-fd** [SteveSyfuhs/Kerberos.NET#194]
Is it possible to authenticate using CredentialCache.DefaultCredentials ?
https://docs.microsoft.com/ru-ru/dotnet/api/system.net.credentialcache.defaultcredentials?view=netstandard-2.0
To use credentials for the current security context in which the application is running without the need to provide credentials.

**Comment by SteveSyfuhs** [comment]
No. Windows does not expose raw credentials for use by external libraries. If you need SSO from within Windows you should stick to SSPI.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SteveSyfuhs** [comment]
Incidentally support for this has partially been added where it'll hand off all Kerberos work to SSPI if you want.

```csharp
var client = new KerberosClient() { Cache = new LsaCredentialCache() };
```

Or

```csharp
var config = Krb5Config.Default();
config.Defaults.DefaultCCacheName = "MSLSA"

var client = new KerberosClient(config);
```

Or

```
[libdefaults]
default_ccache_name = MSLSA
```
