### ISSUE TITLE
Include support for PA_S4U_X509_USER

### ISSUE THREAD

**Issue by 0xe7** [SteveSyfuhs/Kerberos.NET#197]
**Is your feature request related to a problem? Please describe.**
S4U2Self requests when performing delegation through SQL server include the PA_S4U_X509_USER PA-DATA section

**Describe the solution you'd like**
A working implementation of PA_S4U_X509_USER

**Describe alternatives you've considered**
I've tried implementing this manually but am struggling to get the checksum right, the documentation (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-sfu/cd9d5ca7-ce20-4693-872b-2f5dd41cbff6) says it's simply a checksum of the encoded S4UUserID within the user-id field but it isn't working for me.

**Comment by SteveSyfuhs** [comment]
I've started looking at this and have a first pass here: https://github.com/dotnet/Kerberos.NET/pull/199/files

I haven't had a chance to test it against a real environment yet. Will focus on that next, but that requires getting something set up.

If you have the time and inclination to verify it please do.

**Comment by 0xe7** [comment]
So I had to modify it to insert the PA_S4U_X509_USER even when a certificate isn't being used (the behaviour I'm seeing from SQL server when requesting an S4U2Self, it seems to insert both the PA_S4U_X509_USER as well as the PA-FOR-USER PA-DATA fields). With your implementation I'm getting an KRB_AP_ERR_MODIFIED error, the same as with my implementation:

 
![error](https://user-images.githubusercontent.com/13423848/94351425-3dd9ce00-0050-11eb-9b85-906637b523c5.png)

The left is executing the S4U2Self with Kerberos.NET (the PA_S4U_X509_USER section), on the right is a genuine S4U2Self when executing a query through SQL server over a DB link.

**Comment by SteveSyfuhs** [comment]
Hmm, okay. I'll have to debug AD and see what it's complaining about. How do you have SQL set up?

**Comment by 0xe7** [comment]
I have 2 SQL servers (SQL1 and SQL2), one running as an AD user (sqlservice) (for ease, so I can just enter the password rather than using the machine account hash when trying to imitate it), setup resource-based contrained delegation to allow sqlservice to delegate to SQL2, then a DB link setup from SQL1 to SQL2 to use the current user's security context, then just login to SQL1 as any user and execute a query over the link. The service account will perform the S4U.

**Comment by SteveSyfuhs** [comment]
Oh I see, it doesn't even use a certificate. That explains some things. Let me have a look.
