### ISSUE TITLE
[QUESTION] How can I use this package to use in my WCF client?

### ISSUE THREAD

**Issue by AlbertoMonteiro** [SteveSyfuhs/Kerberos.NET#20]
I am using a SOAP webservice with standard WCF tooling in  Visual Studio.
On my machine that is in Active Directory, passing the Windows Credentials, it works properly, but when I send my app to other PC that is no in AD, the auth fail.

The SOAP webservice, use Kerberos protocol to authenticate users, I was trying to use this in standard SOAP client, but I didn't find a way.

How can I achieve that?

**Comment by SteveSyfuhs** [comment]
This isn't a client library. It's a server side token validator.

**Comment by AlbertoMonteiro** [comment]
@SteveSyfuhs thanks
