### ISSUE TITLE
Kerberos AES256 algorithm

### ISSUE THREAD

**Issue by Vsevosemnog** [SteveSyfuhs/Kerberos.NET#204]
Good day.

Could you please help me with my question:

I`ve learned and read a lot about your Kerberos .Net implementation, but haven`t found the answer.

If we look at AES256 algorithm implementation we`ll find that in some steps it uses n-fold algorithm in order to derive some help-keys. For example, the word "kerberos" is given to n-fold algorithm to make a string of bytes.

During making the key for message encryption with the help of AES256 algorithm we use n-fold algorithm not only for the word "kerberos", also we use it with constants, which are depended on the type of the packet (AS_REG,AS_REP,TGS_REP). Where can i find these constants, which a given on the entrance of n-fold algorithm in order to make intermediate keys?

 `private static ReadOnlyMemory<byte> DR(ReadOnlyMemory<byte> key, ReadOnlyMemory<byte> constant, int keySize, int blockSize)
        {
            var keyBytes = new Memory<byte>(new byte[keySize]);

            ReadOnlyMemory<byte> ki;

            if (constant.Length != blockSize)
            {
                ki = NFold(constant.Span, blockSize);
            }
            else
            {
                ki = constant;
            }

            var n = 0;

            do
            {
                ki = AESCTS.Encrypt(ki, key, AllZerosInitVector);

                if (n + blockSize >= keySize)
                {
                    ki.CopyTo(keyBytes.Slice(n, keySize - n));
                    break;
                }

                ki.CopyTo(keyBytes.Slice(n, blockSize));

                n += blockSize;
            }
            while (n < keySize);

            return keyBytes;
        }`

I have a very important issue with it, could you please help me?

**Comment by SteveSyfuhs** [comment]
The constant is derived in `dk()`:

```csharp
private static ReadOnlyMemory<byte> DK(ReadOnlyMemory<byte> key, KeyUsage usage, KeyDerivationMode kdf, int keySize, int blockSize)
{
    using (var constantPool = CryptoPool.RentUnsafe<byte>(5))
    {
        var constant = constantPool.Memory.Slice(0, 5);

        Span<byte> span = constant.Span;
        span.Clear();
        BinaryPrimitives.WriteInt32BigEndian(span, (int)usage);

        constant.Span[4] = (byte)kdf;

        return DK(key, constant, keySize, blockSize);
    }
}
```

The per-request value relies on `KeyUsage`. That's defined in an enum in the cryptography folder.

**Comment by Vsevosemnog** [comment]
So, the constant consists of 5 bytes.

There are a lot of values in KeyUsage file

as i can understand
for as_reg packet the constant is PaEncTs = 1
and for as_rep EncAsRepPart = 3

and they have this form:
0x00 0x00 0x00 0x00 0x01
0x00 0x00 0x00 0x00 0x03

But i can`t understand, which constants are for another packets. For example TGS_REP and so on. 
It`s not trivial task to understand : there are a lot of values in KeyUsage

Could you please explain

**Comment by SteveSyfuhs** [comment]
You know there's a spec, right?

https://tools.ietf.org/html/rfc4120

It's pretty clear about what to use.

________________________________

**Comment by Vsevosemnog** [comment]
I`ve read a lot of rfc about Kerberos and couldn`t find really detailed explanation about how AES algorithm works.

there are several constants in its calculation, which are not described

**Comment by SteveSyfuhs** [comment]
AES is defined in https://tools.ietf.org/html/rfc3962

Which relies on https://tools.ietf.org/html/rfc3961 for general implementation details.

________________________________

**Comment by Vsevosemnog** [comment]
I know about this standards.
Thanks a lot, i  will try to find out.

But, actually, there is not step-by-step explanation of making key with the help of AES algorithm, which is used in Kerberos

**Comment by SteveSyfuhs** [comment]
Specs generally don't provide step by step guidance. The 3961 spec is however pretty clear about how the KDF operates. 3962 provides AES-specific guidance, which isn't actually notably different because it just changes algorithm parameters. 4120 specifies which key usage types should be used during particular message flows.

________________________________

**Comment by Vsevosemnog** [comment]
Thank you for explaning me

But I`ve found your project here, and i think that it will be very clear step by step algorithm of derivation of the key and the values of constants.

I know about these RFCs, but interested in details, which are provided in the project. But i can`t understand some things in functions in order to find the values of constants
