### ISSUE TITLE
Can't provide configuration from code

### ISSUE THREAD

**Issue by macsux** [SteveSyfuhs/Kerberos.NET#205]
New versions removes `string kdc` parameter from `KerberosClient` and instead uses `Krb5RealmConfig` object. This object has all fields with private setters. It's impossible to build it up in code without resorting to using reflection. Ex

```
var config = Krb5Config.Default();
var realm = new Krb5RealmConfig();
var kdcList = new List<string> {kdc};
realm.GetType().GetProperty(nameof(realm.Kdc)).SetValue(realm, kdcList);
var realms = new Dictionary<string, Krb5RealmConfig>();
realms.Add("ALMIREX.DC", realm);
config.GetType().GetProperty(nameof(config.Realms)).SetValue(config, realms);
var client = new KerberosClient(config);
```

Please change config to have public setters, or introduce a builder if the intent is to keep config immutable. If creating an instance without calling `Default()` many properties are null, causing runtime errors. Consider making constructor internal to avoid misuse of API. 

It would also be nice to not have to provide the realm as part of config. I understand that the new config object expands by allowing multiple realms/kdc, but old config style allowed for extra simplicity when targeting just one realm.

**Comment by SteveSyfuhs** [comment]
The setters are correct. Each object instance is already set internally, and the dictionary is special in that you can just call it like this:

```csharp
config.Realms["REALM.COM"].Kdc.Add("10.21.1.3");
```

I suppose it makes sense to make this a bit easier to create, or at least more obvious that `.Default()` should be called instead.

Alternatively you have 

```csharp
var client = new KerberosClient();
client.PinKdc("REALM.COM", "10.21.2.4");
```

Keeping a single KDC parameter on the client introduced too many conflicts with everything provided in the config.

**Comment by SteveSyfuhs** [comment]
I've created a PR that makes this easier. It lets you do something like:

```csharp
var config = new Krb5Config();

config.Realms["REALM.COM"].Kdc.Add("10.21.1.3");
```
