### ISSUE TITLE
NTLM Dummy record

### ISSUE THREAD

**Issue by Zubastic** [SteveSyfuhs/Kerberos.NET#209]
**Is your feature request related to a problem? Please describe.**
https://github.com/dotnet/Kerberos.NET/issues/29

At this issue we having problem: if computer doesn't have any SPN assigned, client send NTLM broken token. For debug clarity, I guess, it would be ok to add information details about SPN.

**Describe the solution you'd like**
Add additional debug info if token starts with ```TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAA```

**Comment by SteveSyfuhs** [comment]
It should detect NTLM already and throw an error. Is it not doing that?

________________________________

**Comment by Zubastic** [comment]
> It should detect NTLM already and throw an error. Is it not doing that?

It throw generic error that NTLM not supported. But I think that it would be good if error with info about missing SPN would be thrown.

**Comment by SteveSyfuhs** [comment]
The issue is this library has no idea if it's because of a missing SPN or some other reason. Annoyingly it's also impossible to guess what the SPN should be because its dependent on what the service in question is and the library doesn't know what that is.

Couple solutions:

 * in this code change NtlmContextToken to throw (bold added): throw new NotSupportedException("NTLM is not supported. **Is your service account missing an SPN registration?**");
 * In your code catch `NotSupportedException` and check if it contains NTLM and indicate to caller its maybe because there's no SPN registered.

**Comment by Zubastic** [comment]
Hmmm, I guest, I could check if token starts with `TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAA` and throw another error.

**Comment by SteveSyfuhs** [comment]
There's a helper method `NtlmMessage.CanReadNtlmMessage(data)` that might be of use to you. It'll parse it properly instead of doing a string comparison (there's no guarantee that string value wouldn't change in the future).

**Comment by Zubastic** [comment]
> It'll parse it properly instead of doing a string comparison (there's no guarantee that string value wouldn't change in the future).

I want to check if it dummy string with empty login + domain. I create code to parse:
```c#
var b = Convert.FromBase64String("TlRMTVNTUAABAAAAl4II4gAAAAAAAAAAAAAAAAAAAAAGA4AlAAAADw==");
using (var ms = new MemoryStream(b))
{
    using (var br = new BinaryReader(ms))
    {
        string GetValue(BinaryReader reader)
        {
            var length = reader.ReadInt16();
            var alloc = reader.ReadInt16();
            if (alloc != length)
            {
                throw new ArgumentOutOfRangeException(nameof(alloc));
            }
            var offset = reader.ReadInt32();
            var currentOffset = reader.BaseStream.Position;
            reader.BaseStream.Position = offset;
            var data = reader.ReadBytes(length);
            var name = Encoding.UTF8.GetString(data);
            reader.BaseStream.Position = currentOffset;
            return name;
        }
        var header = Encoding.UTF8.GetString(br.ReadBytes(8));
        if (header.StartsWith("NTLMSSP"))
        {
            var ver = br.ReadInt32();
            switch (ver)
            {
                case 1:
                    var flags = br.ReadInt32();
                    var domain = GetValue(br);
                    var workstation = GetValue(br);
                    var major = br.ReadByte();
                    var minor = br.ReadByte();
                    var build = br.ReadInt16();
                    var unk = br.ReadInt16(); //always zero
                    var osVer = $"OS Ver: {major}.{minor} Build: {build}";
                    break;
                case 2:
                    break;
                case 3:
                    break;
                default:
                    throw new ArgumentOutOfRangeException(nameof(ver));
            }
        }
    }
}

```

**Comment by SteveSyfuhs** [comment]
That works too.
