### ISSUE TITLE
Pleace can you show, how to get kerberos key from firefox in asp.net core app?

### ISSUE THREAD

**Issue by megafetis** [SteveSyfuhs/Kerberos.NET#21]
Pleace can you show how to get kerberos key from firefox in asp.net core app? 
I want to authenticate user in asp.net core
Or another ways to authenticate user in linux systems

**Comment by SteveSyfuhs** [comment]
Firefox or any browser has no bearing on the key.

I recommend reading through these posts to get an understanding of how this all works: https://syfuhs.net/tag/kerberos-net/
