### ISSUE TITLE
Overrided MR

### ISSUE THREAD

**Issue by Zubastic** [SteveSyfuhs/Kerberos.NET#210]
**Describe the bug**
https://github.com/dotnet/Kerberos.NET/pull/166

MR overrided by 0b83e6b2e4183e17daece5b3cf12187a929b1771.

**Comment by SteveSyfuhs** [comment]
This is a code regression because of the merge? Should be easy to fix.

**Comment by Zubastic** [comment]
> This is a code regression because of the merge? Should be easy to fix.

Yep.

**Comment by SteveSyfuhs** [comment]
This was fixed with #233
