### ISSUE TITLE
System.Security.SecurityException: Invalid Checksum

### ISSUE THREAD

**Issue by spplecxer** [SteveSyfuhs/Kerberos.NET#215]
Hi Steve,
First thanks for this great project.
I used your tester tool code to build a simple exe with novalidate option. It takes the keytab and the kerb header and should return the upn from the ticket. I'm only interested in getting the UPN from the header to do my stuff. 
I tested on my lab and it works perfect. I tried in a different environment and I'm getting this error:

System.Security.SecurityException: Invalid Checksum
   at Kerberos.NET.Entities.RC4DecryptedData.Decrypt(Byte[] k1, Byte[] ciphertext, KeyUsage keyType)
   at Kerberos.NET.Entities.RC4DecryptedData.Decrypt(KeyTable keytab)
   at Kerberos.NET.KerberosRequest.Decrypt(KrbApReq token, KeyTable keytab)
   at Kerberos.NET.KerberosRequest.DecryptNegotiate(NegTokenInit negotiationToken, KeyTable keytab)
   at Kerberos.NET.KerberosRequest.Decrypt(KeyTable keytab)
   at Kerberos.NET.KerberosValidator.<Validate>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kerberos.NET.KerberosAuthenticator.<Authenticate>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kerberos.NET.KerberosAuthenticator.<Authenticate>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApp3.Program.<MainAsync>d__1.MoveNext() 
The Zone of the assembly that failed was:
MyComputer

It's hitting against the wall against the RC4 decryption.
Keytab was generated with no errors with crypto all and I see these in the keytab file:

"EncryptionType": "DES_CBC_CRC",
"EncryptionType": "DES_CBC_MD5",
"EncryptionType": "RC4_HMAC_NT",
"EncryptionType": "AES256_CTS_HMAC_SHA1_96",
"EncryptionType": "AES256_CTS_HMAC_SHA1_96",

and this:
"FileVersion": 2,
"KerberosVersion": 5,

On the decrypted header I see this:

            "EncPart": {
              "EType": "RC4_HMAC_NT",
              "KeyVersionNumber": 2,

and 
          "Authenticator": {
            "EType": "RC4_HMAC_NT",
            "KeyVersionNumber": null,

I also see the other encryption types.

I tried with different keytab files and I'm hitting the same error.

My guess it that RC4 is disabled in the target AD but I'm not sure of that.
What am I missing? 
I'll go on comparing stuff between my working lab and the target AD but if you can spot the missing piece that would great.
I went back and compiled your full code with no modification and I got the same error.
I run it like this: consoleapp.exe keytab kerbheader novalidate 
Thanks.

**Comment by SteveSyfuhs** [comment]
If RC4 is disabled it'll usually switch to AES256. The library detects what etype the message was sent with though, so presumably if you're getting an RC4 error out of the library on the other domain that means it did actually use RC4. RC4 is an incredibly simple encryption scheme, so the _only_ thing that causes it to fail is the password being wrong (or different between domains).

**Comment by spplecxer** [comment]
Thanks for the quick reply.
Which password is that? I did create the keytab file without any error and usually when the password provided during keytab file creation is wrong the ktpass tool throws an error. 
If that's the we are talking about I will have to check.

**Comment by SteveSyfuhs** [comment]
The kerberos ticket from AD is encrypted using the secret in the keytab. That secret is the password of the user account.

________________________________

**Comment by spplecxer** [comment]
Ok then that's what I was talking about then. I made sure the guy who ran the command used the right password. Will use the password tomorrow to test it then recreate the keytab file. Will update when I'm done. Thanks a bunch.

**Comment by spplecxer** [comment]
Ok so I tested the ktpass with a bogus password and sure enough the file was created without any errors. In fact what I initially did was trying a bogus password during the keyatb creation an I ended up having issues but that was just to see how it behaves with a bogus keytab. I then switched to using the correct password then I generated the exe file and tested ok.
I just checked the password I sent to the AD guy to use is correct. The password has some special characters in it of course and this did trigger a ktpass error then we enclosed the password in quotes and it worked. I just tested the same password enclosed in quotes in my lab and it does work too. So tomorrow I will re-create the file making sure the password is oK. Will update with the progress. 
Thanks.

**Comment by spplecxer** [comment]
Ok found my pit :-)
I was thinking using a keytab with a single account against user tickets obtained for multiple service account was somehow possible and went deep down the pit with using the same password for all my service accounts in my lab !!! the result of this is one keytab was valid for all tickets because it is using the same password to decrypt the tickets. when I switched to another account with a different password I hit the wall !! 
I need to decrypt tickets targeting multiple web applications running under different service accounts and different passwords.
I can always loop through the keytab files until I get the expected result but is it possible to use a single keytab file with multiple principals/service accounts? I will look into this tomorrow.

**Comment by SteveSyfuhs** [comment]
Sure. A keytab is an SPN,etype=>key mapped file. Kerb.net will try and find a suitable key based on spn and etype, but will eventually fall back to just etype if it cant find one that explicitly matches.

I don't know if ktpass can generate this for you though.

________________________________

**Comment by spplecxer** [comment]
Dumb question: is there a way of getting just the domain name and the user name (upn otherwise) using the kerberos.net dll and a dummy keytab. I mean a keytab not generated for the service account targeted in the kerberos ticket submitted by the user?

**Comment by spplecxer** [comment]
ok managed to get my stuff together using ktpass and the parameter /in.
example of a three prinicipal keytab file using three service accounts and three spns:
ktpass -princ HTTP/site0.mygreatwebapp.com@TMPDOMAIN.COM -mapuser tmpdomain\srvaccount0 crypto all -ptype KRB5_NT_PRINCIPAL -pass pass0 -out D:\tmp\Kerberos\initial.keytab
ktpass /out D:\tmp\Kerberos\merged1.keytab /mapuser tmpdomain\srvaccount1 /princ HTTP/site1.mygreatwebapp.com@TMPDOMAIN.COM /pass pass1 /ptype KRB5_NT_PRINCIPAL /in D:\tmp\Kerberos\initial.keytab
ktpass /out D:\tmp\Kerberos\merged_final.keytab /mapuser tmpdomain\srvaccount2 /princ HTTP/site2.mygreatwebapp.com@TMPDOMAIN.COM /pass pass2 /ptype KRB5_NT_PRINCIPAL /in D:\tmp\Kerberos\merged.keytab

The executable I made based on your code works fine. I just removed the arguments I don't need and forced the use of novalidate.
If you have an answer to my question above that would be great; Otherwise I can mark this as solved.
Then another question arises: how would you secure the keytab file from being exposed to some prying eyes other than the obvious server security stuff?

**Comment by SteveSyfuhs** [comment]
I don't really understand the first question. The ticket is encrypted to the service account password. You either know it and can decrypt it or you don't and can't.

As for protecting the file: that's just normal file protection stuff. Nothing special. Doesn't technically have to be a file. Could be stored in a db or wherever.

________________________________

**Comment by spplecxer** [comment]
Yes got that. Forget about that question :-)
I'll be using the multiple principals/spns keytab file on a server with admin access only.
Thanks for your help and keep up the good stuff.
