### ISSUE TITLE
Generate TGT and "Authenticator"

### ISSUE THREAD

**Issue by ScotMac** [SteveSyfuhs/Kerberos.NET#24]
Hi Steve, would your package work for the strictly client side functionality of generating a particular service TGT and the associated "Authenticator" to then send to the server service for authentication?

If so, do you mind pointing me to the calls that i would use to do it? 

Thanks, Scot

**Comment by ScotMac** [comment]
For reference, here are the MIT Kerberos5 APIs that we are currently using to do it for non-.NET/non-Core current implementations, where the final call (krb5_mk_req_extended) will generate what i calling the "authenticator" bytes:

krb5_init_context((krb5_context *)&context);
krb5_sname_to_principal(context, (char *) 0, (char *) 0, KRB5_NT_SRV_HST, &server);
krb5_get_default_realm(context, &therealm);
krb5_cc_resolve(context, CCNm_, &ccache);
krb5_cc_get_principal(context, ccache, &client); 
krb5_auth_con_init(context, &auth_context);
krb5_copy_principal(context, server, &creds.server);
krb5_copy_principal(context, client, &creds.client);
krb5_get_credentials(context, 0, ccache, &creds, &credsp);
krb5_mk_req_extended(context, &auth_context, auth_options, &cksum_data, credsp, &outbuf);

**Comment by SteveSyfuhs** [comment]
No sorry. There's no generation in this library. All it does is validate service tickets.

**Comment by ScotMac** [comment]
Thanks for the quick response Steve! Any plans to extend it to the client side (generation)?

**Comment by SteveSyfuhs** [comment]
This is a common question. Assume no. I would like to, but don't have the time.

**Comment by ScotMac** [comment]
Understandable. 

Sorry, last question: It appears from my very quick look at your code that you are doing this all in C# (ie, not relying on any other (C) library). Is that correct? If so, how hard do you think it would be to do the work for the client side (generation all in C#)?

**Comment by SteveSyfuhs** [comment]
The language choice is not a problem here. Kerberos uses ASN.1 for all its messages, which is just a PITA to work with. This library also only has an ASN.1 parser, so someone would need to build a way to generate the messages. That's currently the biggest hurdle. There's a ton of Interop work to account for as well.

**Comment by ScotMac** [comment]
Yes, my point wasn't language, but instead whether it is an ALL MANAGED solution. Sounds like it is. Thanks for the info on the complexity.
