### ISSUE TITLE
use with .net forms auth?

### ISSUE THREAD

**Issue by 84pennies** [SteveSyfuhs/Kerberos.NET#25]
Hi there, I am new to all this stuff (kerberos). But I have been working on a .net Forms Auth application for 6 years. Recently the need to be able to validate a kerberos ticket has been asked of us and I was curious if there's some simple snippets you could provide that would point me in the right direction (without needing to upend our current authentication method). The samples provided are all using claims and I am not totally sure how that would port to forms auth/cookie auth.

We typically validate a user by username/password (sometimes through AD) and then create a forms auth ticket that is saved as a cookie and used to validate future requests.

Assuming we can validate the kerberos ticket, we can just create a session with (assuming here) a username?

Any guidance would be greatly appreciated.

**Comment by SteveSyfuhs** [comment]
Yes, the simplest process would be to just grab the username out of the authenticated identity and create a forms ticket based on that username. My only caution is that the incoming username will probably need to be mapped to an existing user as the formats may be different. 

https://github.com/SteveSyfuhs/Kerberos.NET/blob/master/Samples/KerberosWebSample/KerberosEndToEndMiddleware.cs Is a pretty good starting point.
