### ISSUE TITLE
KeyTab parser do not support a negative length entries

### ISSUE THREAD

**Issue by aptukovainur** [SteveSyfuhs/Kerberos.NET#254]
**Describe the bug**
In the krb5.keytab file, according to the documentation, there can be elements with the specified negative length: 

> A negative length indicates a zero-filled hole whose size is the inverse of the length.

https://web.mit.edu/kerberos/krb5-devel/doc/formats/keytab_file_format.html

**To Reproduce**
Get file with negative length, as:
![image](https://user-images.githubusercontent.com/84389740/122213510-79f4dd80-cec2-11eb-8579-1de11d789ce8.png)

```
        public KeyEntry(BinaryReader reader, int version)
        {
            if (reader == null)
            {
                throw new ArgumentNullException(nameof(reader));
            }

            this.Length = ReadInt32(reader);
```
Create KeyEntry will cause exeption
```
 System.ArgumentOutOfRangeException: Non-negative number required. (Parameter 'count')
at System.IO.BinaryReader.ReadBytes(Int32 count)
at Kerberos.NET.Crypto.KeyEntry.ReadKey(BinaryReader reader) in D:\a\1\s\Kerberos.NET\Crypto\KeyEntry.cs:line 118
```

**Expected behavior**
This entities will be missed

**Comment by SteveSyfuhs** [comment]
I haven't ever seen files like this in the real world. How common are they? What produces them? Can you share a sample file?

**Comment by aptukovainur** [comment]
This file creating when our server (AstraLinux) registered in domain controller (Active Directory) of our company. First time its worked normal until it was automatically updated by the company's security policy. After that such lines appeared in it.
Unfortunately, due to policy of the company, I cannot share this file.
P.S. another apps working normal with this keytab-file

**Comment by SteveSyfuhs** [comment]
Okay, I think I have a fix for this. Are you able to test a branch of this separate from the nuget? If so can you give it a try with branch `bugfix/keytab-neg-length`

**Comment by aptukovainur** [comment]
Yes i can test it, I will write later

Update: Yes, its works!

**Comment by aptukovainur** [comment]
When to expect new version on nuget?

**Comment by SteveSyfuhs** [comment]
Were you able to verify it works privately?

**Comment by aptukovainur** [comment]
Yes, I update my comment :

> Update: Yes, its works!

**Comment by SteveSyfuhs** [comment]
Ah okay. I'll merge it in now and that will kick off a new nuget package. Should see something in the next 10 minutes.

**Comment by SteveSyfuhs** [comment]
Nuget package v4.5.110.
