### ISSUE TITLE
Docs - Cross-realm service ticket retrieval

### ISSUE THREAD

**Issue by margod** [SteveSyfuhs/Kerberos.NET#256]
It is not clear from documentation whether cross realm retrieval of service ticket is supported or NOT.

I have probably quite common use case within enterprise usage scenario, where user from realm1.local needs to access service from realm2.local.

Looking at implementation ( [/Kerberos.NET/Client/KerberosClient.cs - 563](../blob/develop/Kerberos.NET/Client/KerberosClient.cs#L563) ) it look like TGS_REQ is always send to KDC of realm of user rather than KDC of service arising from second realm.

**Comment by SteveSyfuhs** [comment]
Referrals are supported and work just fine.

https://github.com/dotnet/Kerberos.NET/blob/794fcd2a944aeeb7f3dea70485128fbe23e02023/Kerberos.NET/Client/KerberosClient.cs#L596-L610

**Comment by margod** [comment]
Misunderstanding of error related to weak crypto being used for cross-realm trust. Clearly referrals are supported.
