### ISSUE TITLE
Encryption supported but received error KDC_ERR_ETYPE_NOSUPP

### ISSUE THREAD

**Issue by NeeleshkumarB** [SteveSyfuhs/Kerberos.NET#258]
**Describe the bug**
Currently using .Net 461 console app and using kerberos client to get service ticket. Authentication is done using keytab file. Authentication works but when requested for service ticket ERROR KDC_ERR_ETYPE_NOSUPP is received.

Code
Sample code, sorry for the screenshot. 
![16275528009395029146079719478312](https://user-images.githubusercontent.com/10509828/127472723-ae6e3344-728f-48db-8872-84b4f44312bb.jpg)

**Expected behavior**
Service ticket request should succed as the encryption type is supported by kerberos server. 

**Screenshots**
![16275524463153876776120230694409](https://user-images.githubusercontent.com/10509828/127471819-786db762-7574-4d2a-ad83-fc9d95168d56.jpg)

**Additional context**
Windows 10 1909

**Comment by SteveSyfuhs** [comment]
What does the trace log show and what's in the krb5.conf file?

**Comment by NeeleshkumarB** [comment]
Kerb5.Config has default realm and forwardable tags set along with domain-realm tag as well. 
In trace it is observed that tcpkerberostransport was used to connect to tgs to get service ticket. 
Connection was a success. In the next step, when requesting for service ticket, mentioned error is observed. 
I also had a look at code, when a kerberos protocol exception occurs, other supported encryption types are Not tried to request service ticket. Is there any particular reason that I should be aware of.? 
Note: same config and keytab file was for spring client for spngeo authentication it works. 
For security reasons I can't share trace information other than what I did.

**Comment by SteveSyfuhs** [comment]
There aren't any additional etypes that can be tried at that point. We send a list of etypes we can support and the KDC either responds with a ticket saying that's fine, or it returns an error saying they aren't supported. At that point there aren't any other etypes that can be sent.

Can you capture a network trace and tell me what etypes are being used in the as-req/rep and tgs-req?

**Comment by alexander-kucherov** [comment]
I'm also have such problem.
If I use 4.5.74 everything ok, but from 4.5.105 I get exception

```
Kerberos.NET.KerberosProtocolException : KDC KDC_ERR_ETYPE_NOSUPP: KDC has no support for encryption type
   at Kerberos.NET.Transport.KerberosTransportBase.Decode[T](ReadOnlyMemory`1 response) in D:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportBase.cs:line 70
   at Kerberos.NET.Transport.TcpKerberosTransport.ReadResponse[T](NetworkStream stream, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 127
   at Kerberos.NET.Transport.TcpKerberosTransport.SendMessage[T](String domain, ReadOnlyMemory`1 encoded, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 59
   at Kerberos.NET.Transport.KerberosTransportSelector.SendMessage[T](String domain, ReadOnlyMemory`1 encoded, CancellationToken cancellation)
   at Kerberos.NET.Client.KerberosClient.RequestTgs(RequestServiceTicket rst, KerberosClientCacheEntry tgtEntry, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 943
   at Kerberos.NET.Client.KerberosClient.GetServiceTicket(RequestServiceTicket rst, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 563
   at Kerberos.NET.Client.KerberosClient.GetServiceTicket(String spn, ApOptions options, String s4u, KrbTicket s4uTicket, KrbTicket u2uServerTicket) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 782
```
in log 
```
trce: Kerberos.NET.Client.KerberosClient[0]
      Attempting AS-REQ. UserName = TestUser; Domain = MyDomain; Nonce = 1791496724
```

**Comment by SteveSyfuhs** [comment]
Can you grab a network trace of this attempt? I need to see what etypes the client and server are trying to negotiate.
________________________________

**Comment by alexander-kucherov** [comment]
Sorry, but i can't expose traffic from our corporate network.
I've made full log collect from library
```
trce: Kerberos.NET.Client.KerberosClient[0]
      Attempting AS-REQ. UserName = TestUser; Domain = MYDOMAIN.COM; Nonce = -1157964373
dbug: Kerberos.NET.Transport.ClientDomainService[0]
      Querying DNS _kerberos._tcp.MYDOMAIN.COM
trce: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connecting to mydomain-dc3.MYDOMAIN.COM on port 88
dbug: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connected to mydomain-dc3.MYDOMAIN.COM on port 88
dbug: Kerberos.NET.Client.KerberosClient[0]
      AS-REP PA-Data: EType = AES256_CTS_HMAC_SHA1_96; Salt = MYDOMAIN.COMTestUser;
trce: Kerberos.NET.Client.KerberosClient[0]
      Attempting AS-REQ. UserName = TestUser; Domain = MYDOMAIN.COM; Nonce = 1392362958
dbug: Kerberos.NET.Transport.ClientDomainService[0]
      Querying DNS _kerberos._tcp.MYDOMAIN.COM
trce: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connecting to mydomain-dc1.MYDOMAIN.COM on port 88
dbug: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connected to mydomain-dc1.MYDOMAIN.COM on port 88
dbug: Kerberos.NET.Client.KerberosClient[0]
      EncPart expected to be KrbEncAsRepPart and is actually KrbEncAsRepPart
trce: Kerberos.NET.TicketCacheBase[0]
      Caching ticket until 08/23/2021 17:36:21 +00:00 for kerberos--krbtgt/MYDOMAIN.COM with renewal option until 08/24/2021 07:36:21 +00:00
info: Kerberos.NET.Client.KerberosClient[0]
      Requesting TGS for HTTP/api.MYDOMAIN.COM; TGT Realm = MYDOMAIN.COM; TGT Service = krbtgt/MYDOMAIN.COM; S4U = (null); S4UTicket = (null)
dbug: Kerberos.NET.Transport.ClientDomainService[0]
      Querying DNS _kerberos._tcp.MYDOMAIN.COM
trce: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connecting to mydomain-dc2.MYDOMAIN.COM on port 88
dbug: Kerberos.NET.Transport.TcpKerberosTransport[0]
      TCP connected to mydomain-dc2.MYDOMAIN.COM on port 88
```

**Comment by SteveSyfuhs** [comment]
These logs are unfortunately not helpful. The issue is the KDC isn't liking what's being sent, and these logs don't include them. I need to know what the client is negotiating and what the server is negotiating. The only way is by looking at the messages themselves. I need to see AS-REQ -> body -> encryptiontype and the KRB-ERROR -> edata values.

**Comment by alexander-kucherov** [comment]
> These logs are unfortunately not helpful. The issue is the KDC isn't liking what's being sent, and these logs don't include them. I need to know what the client is negotiating and what the server is negotiating. The only way is by looking at the messages themselves. I need to see AS-REQ -> body -> encryptiontype and the KRB-ERROR -> edata values.

I've just sent it to you by e-mail (steve [@] syfuhs.net)
I can't public it here.

**Comment by SteveSyfuhs** [comment]
I'm not sure if it's a related issue, but part of this thread was taken offline and it was determined that the library was acting properly such that it would prevent itself from falling back to RC4. This is happening for security reasons because RC4 is deprecated and shouldn't be used anymore: https://datatracker.ietf.org/doc/html/rfc8429

You can work around it by setting this configuration property:

```
client.Configuration.Defaults.AllowWeakCrypto = true;
```

The reason it's falling back to RC4 is likely because the service account you're trying to get a ticket to isn't configured to use AES.

**Comment by alexander-kucherov** [comment]
Thanks. It helps me
