### ISSUE TITLE
Failure to parse keytab due to extra padding

### ISSUE THREAD

**Issue by quietust** [SteveSyfuhs/Kerberos.NET#26]
While attempting to parse a keytab acquired using Samba's `net ads join` command (against a Windows Server 2012 R2 DC), only the first key (of type DES_CBC_CRC) was loaded successfully - the second one had garbage values (type 16718, version 81, length 0) because the first key had an extra 4 bytes of padding at the end which weren't being read, and the other 13 weren't loaded at all.

The problem is in Crypto/KeyTab.cs, in the constructor for KeyEntry - the BinaryReader needs to be explicitly seeked past any unread bytes to ensure that it's at the right offset for the next key.

There's actually another bug in that function too: according to various keytab file format documents, the logic for reading a 32-bit Version field at the end of the entry needs to check if there are _at least 4 unread bytes_ available (`Length - bytesConsumedInEntity >= 4`, rather than just `> 0`), and it should probably also ensure that the value is nonzero before using it.

**Comment by SteveSyfuhs** [comment]
Please feel free to codify the fix and submit a PR. 🙂 It may take a bit of time before I can get to it.


________________________________

**Comment by SteveSyfuhs** [comment]
Closing since the PR has been merged. Nuget package update will show up soon.
