### ISSUE TITLE
Build error in sample KDC Host

### ISSUE THREAD

**Issue by G-Booth** [SteveSyfuhs/Kerberos.NET#265]
Build FAILED.

D:\source\Visual Code\Kerberos.NET\Samples\KerberosKdcHostApp\Program.cs(29,17): error CS0117: 'ListenerOptions' does not contain a definition for 'ListeningOn' [D:\source\Visual Code\Kerberos.NET\Samples\KerberosKdcHostApp\KerberosKdcHostApp.csproj]
D:\source\Visual Code\Kerberos.NET\Samples\KerberosKdcHostApp\Program.cs(34,17): error CS0117: 'ListenerOptions' does not contain a definition for 'ReceiveTimeout' [D:\source\Visual Code\Kerberos.NET\Samples\KerberosKdcHostApp\KerberosKdcHostApp.csproj]
    0 Warning(s)
    2 Error(s)

**Comment by SteveSyfuhs** [comment]
Fixed. Compiles now. https://github.com/dotnet/Kerberos.NET/commit/5dc8ed83740d29bcb606f9bf526299658a55ae83
