### ISSUE TITLE
Service credentials and impersonation

### ISSUE THREAD

**Issue by iosgitr** [SteveSyfuhs/Kerberos.NET#30]
I have validator and authenticator working with keytab created from a service account.  Based on that:

- Can I do away with need for keytab somehow if I'm running the Kerberos code in a process already running as the service account?
- Is there anything I can grab after/during validate/authenticate (within ticket object, etc.) that I can use to get an impersonation token?

**Comment by SteveSyfuhs** [comment]
If it's already running as the service account you can just use the Windows API to accept the ticket and impersonate.

This library purposefully bypasses Windows APIs because it's intended to work offline without being able to see a domain controller which limits it's utility when interacting with Windows APIs.

What are you trying to do that requires this library? If it's worthwhile I can investigate what it would take to create the necessary impersonation/token calls.


________________________________

**Comment by iosgitr** [comment]
I'm trying to do the following:

- Self-host (e.g. Service Fabric instead of IIS)
- Load balance so can't use non-IIS HTTP.sys based listener (e.g. HTTP.sys in ASP.NET Core forces kernel mode auth so SPN can't be on shared AD service account) - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-2.2#kernel-mode-authentication-with-kerberos
- Impersonate with ultimate intention of delegating with KCD (I have this working with AD config and normal IIS ASP.NET impersonation but not with anything outside of IIS yet)

**Comment by PeterHalsted** [comment]
@iosgitr couldn't you use something like Group Managed Service Accounts for that?
https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-windows-cluster-windows-security

**Comment by iosgitr** [comment]
@PeterHalsted, gMSAs are great for running services across multiple machines with a common domain security context and automated password management.  I'd still have to solve the same problem though since a self-hosted HTTP.sys process will do kernel mode auth (i.e. SPNs have to be added to computer accounts, not gMSA) regardless of service security context.  Thanks for the suggestion though.

@SteveSyfuhs, thanks!  I have an initial test working now with AcceptSecurityContext and after impersonating, have delegation with KCD working to a back end service, all without depending on IIS.  Awesome library btw although I might be using fewer parts of it for now since your suggestion worked.
