### ISSUE TITLE
Validate Service ticket by using another Computer account and Keytab

### ISSUE THREAD

**Issue by minli1** [SteveSyfuhs/Kerberos.NET#315]
Hi, I am asking how to validate the service ticket with another account(machine account) + keytab file. Any insights appreciated!

What I got now:
1. get the local user service ticket(AP-REQ) by SSPI, like below, say the current logged on user is _**UserA**_, this user can get a service ticket to the current Host with a success.
```
var hostName = Environment.MachineName.ToLowerInvariant();
var context = new SspiContext(spn: hostName);
byte[] tokenBytes = context.RequestToken();
```
2. I have another machine account say **_ComputerB_** and it's a valid keytab file.

My question is how to validate the service ticket got from step 1 by using the **_ComputerB_** the keytab.
Is there any S4U way for validating this? @SteveSyfuhs

**Comment by SteveSyfuhs** [comment]
It's not entirely clear what you're trying to accomplish. You're requesting a ticket to the current host. Is _ComputerB_ the current host? If the current host is not ComputerB then the keytab isn't going to do anything because the ticket is encrypted to that host's own key. You need to request a ticket to _ComputerB_. Only then can you validate the ticket using ComputerB's keytab.

**Comment by minli1** [comment]
Appreciated your quick response. @SteveSyfuhs 
The ComputerB is not the current host so like you said I cannot use the keytab from the ComputerB to validate the ticket for the current host.
I will try to get the service ticket to ComputerB and then use the ComputerB's keytab for the validation. 
Thanks!

**Comment by minli1** [comment]
Hi @SteveSyfuhs Thanks a lot for the hint. I managed to validate the ticket now.
One more question, I am wondering whether there is a way that can leverage from this repo to encrypt the arbitrary message by the service ticket and decrypt the message when validating the service ticket.

**Comment by SteveSyfuhs** [comment]
There are two mechanisms built into the Kerberos protocol for that. 

First is the session key. Both the client and server know the key, so you can use it as a symmetric key for any form of encryption that you want. That's something defined by you.

Second, you can pass in additional authorization data via the ticket or the authenticator. Passing via the ticket requires sending the data to the KDC beforehand, and passing via the authenticator requires just passing it during the AP-REQ. Both require the client to be aware of this data. SSPI doesn't allow you to pass in arbitrary authz data. KerberosClient here also doesn't support that, but it could be modified to do so.

**Comment by minli1** [comment]
Hi Steve, thanks a lot for your kind response so far. @SteveSyfuhs 
I do have another question about the kdecode in bruce, after I click ```request for <local-host>``` , it successfully gave me a ticket for accessing the local host, I assume to validate the local host ticket, I need the host's credential which can get from the LSA, can you confirm that? 
When I click the ```Decode with LSA Secret```, it failed with below, maybe you could give some insights about this?
Thanks in advance!
<img width="1678" alt="image" src="https://user-images.githubusercontent.com/26323691/190675569-37c4bf43-77e7-4855-973d-9c9eb8aaab3f.png">

**Comment by SteveSyfuhs** [comment]
Yes, you need local admin rights to read the machine secret.

**Comment by minli1** [comment]
Thanks, @SteveSyfuhs 
While I used the below code to get a ticket for accessing the local machine,
```
var localHost = Environment.MachineName.ToLowerInvariant();
var context = new SspiContext(spn: localHost);
byte[] tokenBytes = context.RequestToken()
var ticket = Convert.ToBase64String(tokenBytes);
Console.WriteLine("the ticket is: " + ticket);
```
But when I pasted the ticket string into the kdecode console app and click `Decode with LSA secret`(this time I have the admin rights), the decode failed.
It seems like the LSA secret was fetched with a success but still got a decode failure. I am guessing it may due to the SPN was not matched so the local machine secret cannot decode the ticket, I read from the kdecode code, and it also gets a ticket with `spn=machineName`.
Did I get some wrong here? Thanks. 
<img width="1769" alt="image" src="https://user-images.githubusercontent.com/26323691/190840644-c99c35a3-8786-4735-b008-ff167123cb89.png">

**Comment by SteveSyfuhs** [comment]
No, the issue is that the secret coming out of LSA Secrets is encrypted to non-system components. There is also an undocumented registry key you have to set to tell Windows to give you the secret in clear text. I have left it undocumented because I don't want people abusing it. You will have to search online to find it.
________________________________

**Comment by minli1** [comment]
>the issue is that the secret coming out of LSA Secrets is encrypted to non-system components

@SteveSyfuhs  Hi Steve, if the LSA secrets are encrypted to non-system components then I guess they cannot be used to validate the service ticket for the current host, is that true? if so, why did the kdecode add this option since it actually cannot be used for decoding? Thanks.

**Comment by SteveSyfuhs** [comment]
Because it's a developer tool used for troubleshooting issues, not for general purpose use. If you run it as system then it'll decode things correctly, or if you set the undocumented Windows reg key value it will also decode things correctly.
