### ISSUE TITLE
When trying to authenticate within the context of IIS Express it hangs.

### ISSUE THREAD

**Issue by VictorK** [SteveSyfuhs/Kerberos.NET#318]
I created a console application to test authentication with user/pass and a keytab, both worked as expected.

When using the same code (2-3 lines) in an ASP.NET application when client.Authenticate() is called it just hangs.

The main goal is to use a keytab to SSH to a host to run command from a C# ASP.NET REST endpoint.

Any help trying to debug this is greatly appreciated.

**Comment by SteveSyfuhs** [comment]
How are you calling it? Can you share some repro code? There are some upper limits for timeout on the outbound requests so any network-specific hangs should eventually bail out. It could also be a threading issue depending on how you're handling the async portion.
