### ISSUE TITLE
Unable to handle TCP connection resets

### ISSUE THREAD

**Issue by matze-tn** [SteveSyfuhs/Kerberos.NET#322]
**Describe the bug**
First of all: thank you for this valuable software! :-)

We are using a Kerberos.NET.Client.KerberosClient instance to get service tickets from our Active Directory domain controller.
This works without issues if the KerberosClient is constantly in use.
But if our application is idle for about 15 seconds, the next operation over a TCP connection to the domain controller fails with System.IO.IOException and message "Unable to read data from the transport connection".
In Wireshark we can see that TCP connections are reset (RST) by the server after about 15 seconds without traffic.
Is this an issue with the default [TcpConnectionPoolSettings.IdleTimeout](https://learn.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.tcpconnectionpoolsettings.idletimeout) used by KerberosClient and is it possible for us to configure it somehow?

**To Reproduce**
The issue can be reproduced with the following .NET console application acting as Kerberos client using an Active Directory domain controller as KDC server that resets idle TCP connections after 10 seconds. After the first Thread.Sleep(15000) the next call to client.Authenticate() always fails with the above mentioned IOException.
If in the code below Thread.Sleep(15000) is replaced by Thread.Sleep(10000) then the loop will continue without exception indefinitely (this probably depends on server-side settings).
```
class Program
{
    public static KerberosClient client { get; private set; }
    static async Task Main(string[] args)
    {
        IConfiguration config = new ConfigurationBuilder()
            .AddUserSecrets<Program>()
            .AddJsonFile("appsettings.json")
            .Build();
        var _settings = config.GetRequiredSection("KerberosConfiguration").Get<KerberosConfiguration>();
        var kerbConfig = await File.ReadAllTextAsync(_settings.KrbConfigFilePath)
            .ConfigureAwait(false);
        var krbConfig = Krb5Config.Parse(kerbConfig);
        var credentials = new KerberosPasswordCredential(config["username"], config["password"], config["domain"]);
        Console.WriteLine("started");
        ILoggerFactory _loggerFactory = new LoggerFactory();
        client = new KerberosClient(krbConfig, _loggerFactory)
        {
            RenewTickets = true,
            CacheServiceTickets = true,
            CacheInMemory = true,
            Configuration =
                    {
                        Defaults =
                        {
                            AllowWeakCrypto = true,
                            DnsLookupKdc = false
                        }
                    }
        };
        while (true)
        {
            Console.WriteLine("try to authenticate");
            await client.Authenticate(credentials);
            Console.WriteLine("success");
            Thread.Sleep(15000);
        }
    }
}
```

**Expected behavior**
We expected Kerberos.NET to retry at least once to re-establish TCP connections after a reset, and also to use a configurable value for idle timeout to drop stale TCP connections and replace them automatically.

**Screenshots**

**Additional context**
Our issue seems to be related to the following troubleshoot article from Microsoft:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/identity/ldap-kerberos-server-reset-tcp-sessions

**Comment by SteveSyfuhs** [comment]
I just tried this using your code and can't repro it. What does your config file contain? What framework version are you running? 

The library defaults coincide with AD defaults, which is 10s for receive timeout, 2s for send timeout, and 30s for TCP pool scavenging. The linked TcpConnectionPool article is not relevant here, as that is for an entirely different class. This library implements its own client pool.

The code in question is here: https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/Transport/TcpKerberosTransport.cs#L53-L69

We will retry getting a new socket from the pool until we get valid one. The above code has therefore gotten a valid socket and is then attempting to write to it when the remote end closes its side. From our perspective the socket was good, so retrying a write on socket failure is risky.

A couple options you can try fiddling with after you've created the KerberosClient:

```
TcpKerberosTransport.MaxPoolSize = 1;
TcpKerberosTransport,ScavengeWindow = TimeSpan.FromSeconds(1);
```

Though that's probably not an ideal solution because it causes the system to always open new sockets, which can become a burden at high load.

**Comment by matze-tn** [comment]
Thank you for your help!
Content of our krb5.conf (actual server and domain names have been replaced):
```
[libdefaults]
        default_realm = INTERNAL.COMPANY.COM

# The following krb5.conf variables are only for MIT Kerberos.
        kdc_timesync = 1
        ccache_type = 4
        forwardable = true
        proxiable = true
        rdns = false

# The following encryption type specification will be used by MIT Kerberos
# if uncommented.  In general, the defaults in the MIT Kerberos code are
# correct and overriding these specifications only serves to disable new
# encryption types as they are added, creating interoperability problems.
#
# The only time when you might need to uncomment these lines and change
# the enctypes is if you have local software that will break on ticket
# caches containing ticket encryption types it doesn't know about (such as
# old versions of Sun Java).

#       default_tgs_enctypes = des3-hmac-sha1
#       default_tkt_enctypes = des3-hmac-sha1
#       permitted_enctypes = des3-hmac-sha1

# The following libdefaults parameters are only for Heimdal Kerberos.
        fcc-mit-ticketflags = true

[realms]
    INTERNAL.COMPANY.COM = {
        kdc = kdc1.internal.company.com
        kdc = kdc2.internal.company.com
        admin_server = kdc1.internal.company.com
        admin_server = kdc2.internal.company.com
    }
    OTHER-COMPANY.COM = {
        kdc = kdc1.other-company.com
        kdc = kdc2.other-company.com
        kdc = kdc3.other-company.com
        admin_server = kdc1.other-company.com
        admin_server = kdc2.other-company.com
        admin_server = kdc3.other-company.com
    }

[domain_realm]
    .internal.company.com = INTERNAL.COMPANY.COM
    internal.company.com = INTERNAL.COMPANY.COM
    .other-company.com = OTHER-COMPANY.COM
    other-company.com = OTHER-COMPANY.COM
```
We are currently running .NET 5.

**Comment by matze-tn** [comment]
We tried with various settings of `TcpKerberosTransport.MaxPoolSize` and `TcpKerberosTransport.ScavengeWindow` after also switching to .NET 6.
In our tests `MaxPoolSize` seemingly had no impact at all but using a `ScavengeWindow` of 1 second actually improved the situation and we are only very rarely able to reproduce the issue now.
Although you said:

> A couple options you can try fiddling with **after** you've created the KerberosClient

in our application these options are set once at startup **before** creating the KerberosClient instance as both options are static - or are we mistaken/missing something?

Currently we are still trying to identify the root cause of the connection resets as this can only be a temporary workaround in our eyes. Do you have any ideas?

**Comment by matze-tn** [comment]
~~By the way:
We observed this issue only after our admins rolled out the [Microsoft September 2022 cumulative update](https://msrc.microsoft.com/update-guide/releaseNote/2022-Sep) on the Active Directory Domain Controllers. That might just be correlation and not causation but this issue did not happen before that date ...~~
We can rule that out.

**Comment by matze-tn** [comment]
I have attached a Wireshark log with the problematic TCP resets (IPs have been replaced with "Client" and "DC" and some superfluous information has been removed). The issue causing packages are those from the DC to the Client with "[RST, ACK]".
Note that the entries with KRB5KDC_ERR_PREAUTH_REQUIRED are normal as the Client simply resends the request with pre-authentication data afterwards.
[tcpreq_kerberos.txt](https://github.com/dotnet/Kerberos.NET/files/10065634/tcpreq_kerberos.txt)

**Comment by wfurt** [comment]
Is there any firewall or load-balancer inbetween? The RST may be coming from any gear along the way - especially if the connection is idle for some time.

**Comment by matze-tn** [comment]
Good point @wfurt, but we also tested from clients that do not have firewalls or load-balancers between them and the domain controller servers while still being able to reproduce the TCP resets (the attached Wireshark log actually is from one of those clients). According to our infrastructure admins there are only network switches in between.

Could TCP resets also be triggered by a general overload of the used domain controllers?
We do have other applications (e.g., a proprietary middleware written in Java) running that also rely on Kerberos authentication, use the same Active Directory domain controllers, and seem to be working fine though.
