### ISSUE TITLE
AsnWrite EncodeAsMemory?

### ISSUE THREAD

**Issue by dev-2null** [SteveSyfuhs/Kerberos.NET#324]
Hi, I want to ask a stupid question here, from https://github.com/dotnet/Kerberos.NET/blob/5ca2fda76c8d0e49f5bebca10772844df9ac7de6/Kerberos.NET/Entities/Krb/KrbPaEncTsEnc.generated.cs  you have `writer.EncodeAsMemory()` but I couldn't find this method. How can I do this?

I only see `writer.Encode()`, here's what I want to achieve:

```csharp
            var writer = new AsnWriter(AsnEncodingRules.DER);
            var tag = Asn1Tag.Sequence;
            writer.PushSequence(tag);
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            writer.WriteGeneralizedTime(new DateTimeOffset(DateTime.UtcNow, TimeSpan.Zero));
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            return writer.Encode();
```

But I can only get the following error and I couldn't find an answer to solve it:
```csharp
System.InvalidOperationException: Encode cannot be called while a Sequence, Set-Of, or Octet String is still open.
   at System.Formats.Asn1.AsnWriter.Encode()
```

**Comment by SteveSyfuhs** [comment]
The error is probably complaining that you have a sequence still open. You pushed two sequences to the stack but only popped one, so you're still in a write context of the outer sequence.

That particular method is here:
 https://github.com/dotnet/Kerberos.NET/blob/5ca2fda76c8d0e49f5bebca10772844df9ac7de6/Kerberos.NET/Asn1/Experimental/AsnWriter.cs#L185
________________________________
From: dev2null ***@***.***>
Sent: Friday, November 4, 2022 11:33:44 PM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] AsnWrite EncodeAsMemory? (Issue #324)


Hi, I want to ask a stupid question here, from https://github.com/dotnet/Kerberos.NET/blob/5ca2fda76c8d0e49f5bebca10772844df9ac7de6/Kerberos.NET/Entities/Krb/KrbPaEncTsEnc.generated.cs you have writer.EncodeAsMemory() but I couldn't find this method. How can I do this?

I only see writer.Encode(), here's what I want to achieve:

            var writer = new AsnWriter(AsnEncodingRules.DER);
            var tag = Asn1Tag.Sequence;
            writer.PushSequence(tag);
            writer.PushSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            writer.WriteGeneralizedTime(new DateTimeOffset(DateTime.UtcNow, TimeSpan.Zero));
            writer.PopSequence(new Asn1Tag(TagClass.ContextSpecific, 0));
            return writer.Encode();

But I can only get the following error and I couldn't find an answer to solve it:

System.InvalidOperationException: Encode cannot be called while a Sequence, Set-Of, or Octet String is still open.
   at System.Formats.Asn1.AsnWriter.Encode()

**Comment by dev-2null** [comment]
Thank you very much! And do you see any chance to use GeneralString instead of GeneralizedTime with DateTimeOffset to encode timestamp for preauthentication?
```csharp
var time = DateTime.UtcNow.ToString("yyyyMMddHHmmssZ");
writer.WriteCharacterString(UniversalTagNumber.GeneralString, time);
```

I can only get 
```csharp
 System.ArgumentOutOfRangeException: Exception of type 'System.ArgumentOutOfRangeException' was thrown.
Parameter name: encodingType
Actual value was GeneralString.
```

**Comment by SteveSyfuhs** [comment]
What exactly are you trying to accomplish with this code? GeneralizedTime is not just the date value formatted as GeneralizedString. It's actually tagged as a time value, so any parsing of it will rightfully fail if it sees it tagged a string.

**Comment by dev-2null** [comment]
I want to created encoded timestamp like what's being implemented here: <https://github.com/tyranid/Rubeus/blob/master/Rubeus/Commands/CVE_2022_33679.cs#L33-L45> and <https://github.com/tyranid/Rubeus/blob/master/Rubeus/Asn1/AsnElt.cs#L2121>
To parse the raw GeneralString timestamp. I'm not sure if `AsnWriter` can do this with `WriteGeneralizedTime` or `WriteCharacterString`.

**Comment by SteveSyfuhs** [comment]
No, that wouldn't be directly possible. The point of the ASN library is to make it as difficult as possible to manipulate the raw bytes so you're forced to use safer APIs. You could probably hack it together by manipulating the raw data.
________________________________

**Comment by dev-2null** [comment]
Yeah, I noticed that.. but thank you very much for your answers!
