### ISSUE TITLE
Issues with Kerb tickets of different domains.

### ISSUE THREAD

**Issue by ElectricVampire** [SteveSyfuhs/Kerberos.NET#326]
**My environment:**
We are using Oracle library to connect Oracle DB in .Net Core using Kerberos. 
My DB is in **xyz** domain, and I have SPN attached to an account like - oracle/dbservice. (Notice that realm is not attached with it)

My client account which wants to connect to DB is in **abc** domain. My client machine is windows.

**End Problem**
We are getting ORA-12631 error which means user retrieval failed on DB side. https://smarttechways.com/2019/01/24/ora-12631-username-retrieval-failed/, but with same setup Oracle .Net FW lib works just fine.

**Some of my observation**

I did three use cases one with .Net Core which uses Kerberos.NET lib here connectivity with DB fails. UseCase2 is pure .NET FW which works fine and doesn't use Kerberos.NET and Use Case 3 is using .NetCore without purging ticket generated from usecase#2 which also works fine. We don't need SPN attached to client account in UseCase #2 and #3 while its mandatory in UseCase#1 otherwise I get SPN not found error.

Client : C1
Client Domain: ABC
KDC for C1 on windows is : KDC_C1
SPN associated with account C1 : oracle/dbservice
KDC for DB : KDC_DB
Domain for DB : XYZ.NET

**Use Case 1**
_Using .Net Core_

This doesn't work and Oracle Sends ORA-12631. Which means Oracle did not find the user. Maybe ticket is not in correct domain which i realized when compared the ticket with working use case. (Use Case #3)
When i try by just .Net Core - I see following tickets 

Cached Tickets: (2)

#0>	Client: C1@ABC.COM
	**Server: krbtgt/ABC.COM @ ABC.COM**
	KerbTicket Encryption Type: *****
	Ticket Flags 0x40e10000 -> forwardable renewable initial pre_authent name_canonicalize 
	Start Time: *****
	End Time:   *****
	Renew Time: *****
	Session Key Type: *****
	Cache Flags: 0x1 -> PRIMARY 
	**Kdc Called: KDC_C1.ABC.COM**

#1>	Client: C1 @ABC.COM
	**Server: oracle/dbservice @ ABC.COM**  _**=> I think this should be in XYZ as my DB in XYZ**_
	KerbTicket Encryption Type: ****
	Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize 
	Start Time: ****
	End Time:   ****
	Renew Time: *****
	Session Key Type: ****
	Cache Flags: 0 
	**Kdc Called: KDC_C1.ABC.COM** _**=> I think this should be in XYZ as my DB in XYZ**_

**Use Case 2**
_Using .Net FW_

When used Oracle with .Net FW where Kerberos.NET is not used only following ticket came in klist command and it worked.

#0>	Client: C1 @ ABC.COM
	**Server: krbtgt/ABC.COM @ ABC.COM**
	KerbTicket Encryption Type: *****
	Ticket Flags 0x40e10000 -> forwardable renewable initial pre_authent name_canonicalize 
	Start Time: *****
	End Time:   *****
	Renew Time: *****
	Session Key Type: *****
	Cache Flags: 0x1 -> PRIMARY 
	**Kdc Called: KDC_C1   (Notice no domain here)**

**Use Case 3**
_Using .Net CORE after running .Net FW service and not doing klist purge (using tgt generated by .NET FW lib)_
Now once i was able to connect using .NET FW, I stopped service and did not run purge. Now i started my .NET Core service and tried to use the tgt generated by .NET FW. Now connection works just fine and below are tickets generated by Kerberos.NET.

Cached Tickets: (3)

#0>	Client: C1 @ ABC.COM
	**Server: krbtgt/XYZ.NET @ ABC.COM**   **=> This indicates cross realm trust between XYZ and ABC**
	KerbTicket Encryption Type: ****
	Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize 
	Start Time: ****
	End Time:   ****
	Renew Time: ****
	Session Key Type: ****
	Cache Flags: 0x200 -> DISABLE-TGT-DELEGATION 
	**Kdc Called: KDC_C1.ABC.COM**

#1>	Client: C1 @ ABC.COM
	**Server: krbtgt/ABC.COM @ ABC.COM**
	KerbTicket Encryption Type: ****
	Ticket Flags 0x40e10000 -> forwardable renewable initial pre_authent name_canonicalize 
	Start Time: ****
	End Time:   ****
	Renew Time: ****
	Session Key Type: ****
	Cache Flags: 0x1 -> PRIMARY 
	**Kdc Called: KDC_C1 (No domain here)**

#2>	Client: C1 @ ABC.COM
	**Server: oracle/dbservice @ XYZ.NET** _**=> My guess is that we are missing this in UseCase#1**_
	KerbTicket Encryption Type: ****
	Ticket Flags 0x40a10000 -> forwardable renewable pre_authent name_canonicalize 
	Start Time: ****
	End Time:   ****
	Renew Time: ****
	Session Key Type: ****
	Cache Flags: 0x200 -> DISABLE-TGT-DELEGATION 
	**Kdc Called: KDC_2.XYZ.NET**      _**=> My guess is that we are missing this in UseCase#1**_
	
** Question **
How can I generate ticket for use case #2 (.Net Core) to work with oracle. Basically, how can i get #2 ticket of use case #3 in use case #2.
I don't have Realm with SPN (@XYZ.NET), Does that make any difference here?

Any help will be appreciated.

[Update] Adding realm to SPN didn't help, now its failing at Authenticate method only with following error
Kerberos5: Authentication handshake failure at stage: %s--OracleInternal.Network.NetworkException (0x80004005): NA  Kerberos5: Authentication handshake failure at stage: %s
 ---> System.ComponentModel.Win32Exception (1787): The security database on the server does not have a computer account for this workstation trust relationship.
   at Kerberos.NET.Win32.NativeMethods.LsaThrowIfError(Int32 result) in Kerberos.NET\Win32\NativeMethods.cs:line 210
   at Kerberos.NET.Win32.LsaInterop.LsaCallAuthenticationPackageWithReturn(Void* pBuffer, Int32 bufferSize) in Kerberos.NET\Win32\LsaInterop.cs:line 423
   at Kerberos.NET.Win32.LsaInterop.<>c__DisplayClass19_0.<GetTicket>b__0(IntPtr p, Int32 bufferSize) in Kerberos.NET\Win32\LsaInterop.cs:line 352
   at Kerberos.NET.Win32.LsaInterop.WithFixedBuffer[TRet](Int32 bufferSize, Func`3 func) in Kerberos.NET\Win32\LsaInterop.cs:line 381
   at Kerberos.NET.Win32.LsaInterop.GetTicket(String spn, Int64 luid) in Kerberos.NET\Win32\LsaInterop.cs:line 340
   at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem(String key, String container) in Kerberos.NET\Client\LsaCredentialCache.cs:line 98
   at Kerberos.NET.Client.LsaCredentialCache.GetCacheItem[T](String key, String container) in Kerberos.NET\Client\LsaCredentialCache.cs:line 126
   at Kerberos.NET.Client.KerberosClient.GetServiceTicket(RequestServiceTicket rst, CancellationToken cancellation) in Kerberos.NET\Client\KerberosClient.cs:line 577
   at OracleInternal.Network.AnoKerberos.Authenticate(String KRB5Conf, String KRB5CCName, String SN, String Host, Byte[]& kkey)

**Comment by SteveSyfuhs** [comment]
The fact that you have an SPN registered to a service principal in `oracle/dbservice @ ABC.COM` where `dbservice` actually exists in XYZ.COM is going to cause all sorts of problems regardless of what library you use. All Kerberos clients need to resolve an SPN to a service principal to get a ticket that is encrypted to a key the service in question understands. If the wrong principal is chosen, that means the wrong key is chosen, and the service can't decrypt the ticket and auth fails. _Normally_ you don't have the same SPN registered in two separate domains. That causes the system to not understand that it needs to go ask the other domain for the ticket.

Adding the realm to the SPN changes the SPN. Active Directory is doing a literal string comparison of the new value, and nothing is being found by that value. That is what the `The security database on the server does not have a computer account for this workstation trust relationship.` error means when you decode it.

**Comment by ElectricVampire** [comment]
@SteveSyfuhs Thanks for prompt reply.

Earlier SPN was not attached to Ç1@ABC.COM and use case 2 and 3 still worked fine but use case one was throwing KDC_ERR_S_PRINCIPAL_UNKNOWN hence I thought lib is looking for SPN on C1@ABC.COM hence I added it.  We already have SPN in XYZ.NET where we have DB.

By looking at tickets in use case 2 and use case 3 do you think KERBEROS.NET is not able to find the SPN when ticket is requested by client in different domain and its able to do that when tgt from Use case 2 was already present in cache which you can see in use case 3 . 
**As you can see in use case 3, first TGT indicates that there is cross realm trust, so why I am getting KDC_ERR_S_PRINCIPAL_UNKNOWN when SPN was not attached to C1@ABC.COM and was present in XYZ.NET? 
Shouldn't it give me another TGT with cross realm trust in XYZ.NET which later will be used to get service ticket**

**So real question is why in use case 1, krbtgt/XYZ.NET @ ABC.COM was not requested using krbtgt/ABC.COM @ ABC.COM? Does Kdc Called property in ticket has anything to do with this - I observe that in UseCase2 tgt, KDC doesn't have Realm while in UseCase1 we are getting Realm in initial tgt(#0).
It seems like in use case2 was generated from master KDC while in usecase 1 LSA api took it from slave under it which have some domain attached to it.
If issue is with realm attached to KDC how do I make sure tgt is generated from KDC_C1 rather than KDC_C1.ABC.COM or where we can configure kdc called property if we at all allowed to do that.**

If it at all helps following are the list of kerberos methods calls in UseCase1 and UseCase2.
**UseCase1 : .Net Core with Kerberos.Net** => Not working
kerberosClient = new KerberosClient(krb5Config, iloggerFactory);
kerberosClient.set_AuthenticationOptions(kerberosClient.get_AuthenticationOptions())
kerberosClient.set_Cache((ITicketCache) new LsaCredentialCache(krb5Config, (LsaInterop) null, (ILoggerFactory) null));
requestServiceTicket.set_ServicePrincipalName(SN + "/" + Host);
kerberosClient.GetServiceTicket(requestServiceTicket, cancellationToken).GetAwaiter();

**UseCase2 : .Net FW with oracle, this uses Win specific libs** => Working
krb5_init_context(&context);
krb5_sname_to_principal(context, (sbyte*) 0L, (sbyte*) 0L, 3, &server);
krb5_get_default_realm(context, &mrealm);
krb5_cc_resolve(context, ccname, &ccache);
krb5_cc_get_principal(context, ccache, &client);
krb5_auth_con_init(context, &auth_context);
krb5_copy_principal(context, server, (krb5_principal_data**) ((IntPtr) &krb5Creds + 16));
krb5_get_credentials(context, 0, ccache, &krb5Creds, &credsp);
krb5_mk_req_extended(context, &auth_context, SN, &krb5Data1, credsp, &krb5Data2);


**Can you please help me to identify what configuration needs to be done so my connection also works fine like use case 2 and 3 .**

If any more information for these use cases is required like traces, please let me know - I can share them.

**Comment by ElectricVampire** [comment]
@SteveSyfuhs 
Could you please review my above comment and provide some insight on what could be wrong when using oracle + .net core kerberos flow?

**Comment by SteveSyfuhs** [comment]
The second scenario is using MIT Kerberos libraries on Windows. It's not using built-in Windows components. This would be something you need to bring up with the Oracle folks.

**Comment by ElectricVampire** [comment]
@SteveSyfuhs 
Modified https://github.com/dotnet/Kerberos.NET/blob/ee22e51e6ca7b85a88860101a190e828bd114061/Kerberos.NET/Client/LsaCredentialCache.cs#L88
And added not to this  if condition and got the connection working.

Can please check if this should be fixed or something where you can take a deeper look

**Comment by SteveSyfuhs** [comment]
That's interesting. I think I know what's going on then. It's getting caught on a referral path to the other domain. The check is correct, but it's incomplete. It needs to be

If (IsKrbtgt() && !IsReferral()) { return null; }

It's a bit odd that it's getting caught on this as I'd expect the library to skip the referral chasing the second time.

I'll see about getting this updated shortly.
________________________________

**Comment by nitin-jain** [comment]
It is failing to get initial domain cache i.e. even before it goes for referral. In KerberosClient.cs ->GetServiceTicket() when it calls GetCacheItem (very first call in GetServiceTicket) of LsaCredentialCache for krbtgt of first domain, it returns null i.e. lsa.GetTicket(key) is not called due IsKrbtgt() check.

It goes for referral only if it gets hold of tgt of first domain.

**Comment by SteveSyfuhs** [comment]
Hmm odd. It should always be trying to get the service ticket from the cache first. It should only try krbtgt once that returns null.
________________________________

**Comment by nitin-jain** [comment]
If you are looking at cache inside LsaCredentialCach class, it is not
initialized when object is created.  Local system LSA cache is being
bypassed due to IsKrbTgt() check. Does LsaCredentialCache really needs
in-memory cache as it can easily fetch from Local system LSA cache.

In my testing bypassing IsKrbtgt() check when krbtgt/domain.com ticket is
required, and getting ticket from LSA cache worked fine in all scenarios.

I may be missing something,  but if you can relook at the code and get an
early patch for this will be helpful to us.

**Comment by SteveSyfuhs** [comment]
I think that's occurring in the `CopyTicket` path, which is not where the LSA code is supposed to execute. The idea behind the LSA code is that it will always return a ticket as if it were "magically" cached previously. That happens here:

https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/KerberosClient.cs#L573-L579

Either a cached ticket appears, or an exception is raised. There shouldn't be any other result and it should shortcut execution.

What I think you're seeing is it getting into the `CopyTicket` function:

https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/KerberosClient.cs#L1102-L1122

One way or another that should never happen.

**Comment by nitin-jain** [comment]
in case of gMSA, spn linked tgt will not be there in the cache initially (e.g if windows services is started using gMSA account), so this will return blank:
https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/KerberosClient.cs#L573-L579

then it goes for copy ticket with tgt/domain (read tgtcachename). Here it should return windows server domain tgt which is not happening, as LsaCredentialCache has a check IsKrbTgt() then return null:
https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/KerberosClient.cs#L591-L591

If CopyTicket returns domain tgt, then it goes for cross realm referral ticket and rest of the flow works seamlessly.

Steps, i see working:
1. Get spn from another domain (domain other than that of Windows server) <-- this fails
2. Get current domain tgt from LSA cache <-- success if IsKrbTgt() check is removed in [LSACredentialCache.cs](https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Client/LsaCredentialCache.cs#L88))
3. Get referral domain tgt (#L88 is also blocking this, as it is tgt/another domain)
4. use referral domain tgt and ask for spn tgt

I hope it clarifies.

**Comment by ElectricVampire** [comment]
@SteveSyfuhs Were you able to spare some time to look at this issue?

**Comment by ElectricVampire** [comment]
@SteveSyfuhs Any updates on this? do you need anymore information on this?
