### ISSUE TITLE
S4U with current credential

### ISSUE THREAD

**Issue by RoeyAnagal** [SteveSyfuhs/Kerberos.NET#328]
hi 
im trying to use S4U to get a kerberos ticket for a user that i have only his name 
is it possible to authenticate with the current credential instead of password /certificate credential?

**Comment by SteveSyfuhs** [comment]
What is the 'current' credential?

Does this help as an example?

https://github.com/dotnet/Kerberos.NET/blob/9f0216471b1ae04c7e642827018d6f371bf96002/Bruce/CommandLine/KerberosConstrainedDelegationCommand.cs#L93

**Comment by RoeyAnagal** [comment]
The current  credential is the credential of the logged in user that running the application
i need to do somthing like

```
var client = new KerberosClient();
var credential = new KerberosCurrentCredential();
await client.Authenticate(credential);

var s4uSelf = await client.GetServiceTicket( spn:"spn".Text,s4u: "user");
```

**Comment by SteveSyfuhs** [comment]
Yes, that's basically how GetDelegatedServiceTicket works internally. You should be able to call `GetDelegatedServiceTicket` on `s4uSelf` now.
