### ISSUE TITLE
KerberosAuthenticator LSA secret support

### ISSUE THREAD

**Issue by minli1** [SteveSyfuhs/Kerberos.NET#333]
Hi 
Is the LSA secret(machine account) can work with the KerberosAuthenticator to validate a service to access this machine?
It looks like KerberosAuthenticator is working with keytab only?

**Comment by SteveSyfuhs** [comment]
No. If you want to use Windows secrets to verify tickets you should use Windows APIs via SSPI. That's what they're there for.
________________________________
From: min li ***@***.***>
Sent: Friday, February 10, 2023 12:04:51 AM
To: dotnet/Kerberos.NET ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [dotnet/Kerberos.NET] KerberosAuthenticator LSA secret support (Issue #333)


Hi
Is the LSA secret(machine account) can work with the KerberosAuthenticator to validate a service to access this machine?
It looks like KerberosAuthenticator is working with keytab only?

**Comment by minli1** [comment]
Thank you @SteveSyfuhs
I guess the reason why I fail to use LSA secrets to decrypt is that I need to set an undocumented registry key to have a decrypted version of the machine password for decrypt.
https://github.com/dotnet/Kerberos.NET/issues/16#issuecomment-392136678

While regarding the SSPI, I can see there is a [test case](https://github.com/dotnet/Kerberos.NET/blob/develop/Tests/Tests.Kerberos.NET/Win32/SspiTests.cs#L21) to use SSPI on the server side to validate the ticket in the same process, but I guess in practice will it possible on the **service** side to simply validate the ticket via SSPI like below?
```
token - from client
var serverContext = new SspiContext(spn: localhost);
serverContext.AcceptToken(token, out serverResponse);

// auth the ticket with the serverResponse? I doubt the serverResponse is not the machine's credentials
var authenticator = new KerberosAuthenticator(new KeyTable(serverResponse));
var authenticated = await authenticator.Authenticate(token) as KerberosIdentity;
```

**Comment by SteveSyfuhs** [comment]
Yep, that's exactly what you could do.
________________________________
