### ISSUE TITLE
BaseCommand is not setting property values properly and wipes parameter by wrong index

### ISSUE THREAD

**Issue by CNemo7539** [SteveSyfuhs/Kerberos.NET#343]
**Describe the bug**
I noticed that when i try to use kcd command it does not parse parameters correctly. 

**To Reproduce**
Attempt to run outputs message that one parameter or another is missing

**Expected behavior**
Command populates all parameters described with attributes.

**Additional context**
Looked under debugger at BaseCommand.SetProperty value method. Lines 490 - 494. Basically it tries to match names and if name matched to set property value. I do not understand a couple of things here:
1. Why it set parameter value to null once match found. I consider this a side effect.
2. When next value is empty string it attempts to take value of the next parameter... I do know what is the logic here, but on top of this it increments index outside of condition. Basically it also set next parameter value to null. Same here weird side effect...

Any way the simple fix was to move index increment under check of empty value.
i++ should be moved from if(i <parameters.LEngth - 1) scope to under if(string.IsNullOrWhiteSpace(nextValue) scope.

 It is working after that as expected for me. But I would also like to get logic cleaned, which i do not really understand.

**Comment by SteveSyfuhs** [comment]
Hm, interesting. Thanks for opening the bug. Can you share what command line string you used? I'm sure there is a bug in there. It definitely needs some clean up.

**Comment by CNemo7539** [comment]
Well... Values do not matter, but in general, i noticed that I was not able to set --spn-sam, --spn-pass and --delegated. Strange thing was that when i was reordering them i was getting values for one or another. Once i did that simple change I mentioned i am getting all params as expected. Any way, I think that clearing values on parameters DTO passed inside of the method is not a wise thing. This object used in many places in call chain.

Aside from this i am not able to make this command work. It is trying transporters, ending with KDC KDC_ERR_WRONG_REALM: Reserved for future use. KDC KRB_ERR_RESPONSE_TOO_BIG: Response to big for UDP; retry with TCP. Cannot locate a KDC Proxy endpoint for _domain_name_. This information must be in config file, isn't it? I understand this may be last resort, but i do not see attempt get it from config.

I wonder what this command intended to do? AFAIK constrained delegation is configured in active directory. 

I started to look into this code because I have problem when oracle kerberos authenticated user is not able to query data from another database over the link authenticated by kerberos, effectively same user in two databases. As oracle was mentioned in readme, i was hoping to find out something, not sure what :-)

**Comment by SteveSyfuhs** [comment]
Well, the tool here is really just about showing all the pieces working together at a protocol level. It has nothing to do with configuring AD and it's actually not useful beyond maybe showing that KCD can work as expected given the proper users and secrets. Unfortunately, that doesn't directly translate to how any other callers might be using this either.

The fact that you're seeing KDC_ERR_WRONG_REALM is an indicator that you might be crossing a boundary that constrained delegation doesn't support. That specifically is cross-forest boundaries.

As for parameter parsing, yes, this looks like a bug. I'll get a fix up.

**Comment by SteveSyfuhs** [comment]
Fixed in #344
