### ISSUE TITLE
[Question] : How to refresh the ticket and cache file

### ISSUE THREAD

**Issue by ElectricVampire** [SteveSyfuhs/Kerberos.NET#348]
Following is my use case and I am looking for help or guidance for my implementation of cache refresh using Kerberos.NET library

**Use Case:** 
My application is running in an environment where I need to fetch the kerberos cred cache file using an API call. This file is used by Oracle to connect to a database that internally uses Kerberos.NET. Now it's my responsibility to refresh the service tickets and also the cache file making API call and I am looking for the best way to do it.

**What I am thinking might work:**
// Create a KerberosValidator instance
var validator = new KerberosValidator();

// Validate the Kerberos ticket and obtain the decrypted AP Request
var apReq = validator.Validate(cacheBytes);

// Access the ticket and expiration information
var ticket = apReq.Ticket;
DateTime expirationTime = ticket.SessionEnd;
DateTime renewUntilTime = ticket.RenewUntil;

// Get session expired and ticket expired
bool isTicketExpired = expirationTime < DateTime.UtcNow;
bool isCacheExpired = renewUntilTime < DateTime.UtcNow;

If the ticket expired renew the ticket: I haven't figured out how I would do that
If the session expired make an API call and refresh the Cache.

**Questions:**

1. Have you seen such a use case before, if yes can I take a reference from that implementation or any doc reference
2. Do I need to refresh the ticket or should I download the new cache file every time when isCacheExpired timer is about to expire? If I have to refresh the ticket, how do I do that using Kerberos.NET. I see a bool variable for RefreshTicket and background thread but not sure how can I use it.

Any guidance and help here are appreciated

**Comment by SteveSyfuhs** [comment]
Not quite following the scenario. The client owns getting the ticket and refreshing the cache file. The client shouldn't be giving the caller something that is already expired and because of that the validator is at the mercy of whatever the client sends it. Indicating to the caller that the server received an expired ticket is very much an application-specific protocol: https://www.rfc-editor.org/rfc/rfc4120#section-3.2.4

In principle the server can return a KRB-ERROR with a [code](https://www.rfc-editor.org/rfc/rfc4120#section-7.5.9) `KRB_AP_ERR_TKT_EXPIRED` or `KRB_AP_ERR_MODIFIED` to signal to the client that it needs to trigger a refresh, but the application and client need to know to expect such an error.

If this is all occurring on the client, you can always just inspect the ticket cache to see if things have expired. https://github.com/dotnet/Kerberos.NET/blob/develop/Kerberos.NET/Cache/Krb5TicketCache.cs

**Comment by ElectricVampire** [comment]
@SteveSyfuhs 
My apologies for not being clear on first go -

 I can't generate the krb5cc file on machine. Here Credential Cache file is retrieved from API call which is protected via OAuth.
So my first step to call API and get the krb5cc file when my app starts. I will start a background thread - then I wish to know when its going to expire so I can make another API call and replace it. To do that I am relying on `RenewTill` property.

```
KerberosClient client = new KerberosClient(config);
 client.Cache = new Krb5TicketCache("krb5cc_testAccount");
 ((Kerberos.NET.Client.Krb5TicketCache)client.Cache).Krb5Cache.Credentials).Items[0]).RenewTill
```
Question 1: Is above is code is good way to know `RenewTill` property or eventually when krb5cc file is going to expire? So I can make another call to refresh the cache file.

Question 2: Do I need to do anything else? My understanding of kerberos is fairly low but I thought even though I have valid Krb5cc I still need to be worried about refreshing sgtTickets after certain time interval. If that's the case I would like to understand how I can do that? Do I rely on `EndTime` property?

I am sure lot of information which I presented a possible solution to my problem may be incorrect but whole In whole I would like to keep my Krb5cc  file valid by making API calls so oracle client lib keep on making the connection to Database, As of now I tested that Db connection is successful if I fetch the krb5cc file from API, so next task to keep it in valid state by refreshing it.

looking for your help and guidance in solving this problem

**Comment by SteveSyfuhs** [comment]
Yep, that's a perfectly fine strategy. I should note that service tickets are *not* renewed, even though they can be renewed. They just expire out and new tickets are requested. You may want to balance your check against the expiry property too.
________________________________

**Comment by ElectricVampire** [comment]
`I thought even though I have valid Krb5cc I still need to be worried about refreshing sgtTickets after certain time interval. If that's the case I would like to understand how I can do that? Do I rely on EndTime property?`
Do we need to request new sgt from kdc and write it into krb5cc file? If yes, how can I do that?
I'll here rely on `EndTime` property for requesting new sgt if i have to request one

**Comment by SteveSyfuhs** [comment]
If there's a TGT in the cache then you don't need to do anything. The client will automatically get a new ticket when the old one expires. The TGT should automatically be renewing until `RenewUntil`, but once you've hit that you'll have to request a new cache file. If there isn't a TGT in the cache then you can't do anything other than get a new cache file.

**Comment by ElectricVampire** [comment]
Thanks for confirming renewal, I have already implemented the logic to call API once I am 80% of time RenewUntil.

Sorry for lot of questions -
Initially for sure there is a TGT as I was able to make the DbConnection, how do I know when it's going to expire or go away? Do I have to check EndTime property? Its 7 times smaller than my RenewUntil property value.

**Comment by SteveSyfuhs** [comment]
> how do I know when it's going to expire or go away? Do I have to check EndTime property? Its 7 times smaller than my RenewUntil property value.

Correct. TGTs are intended to expire regularly and be renewed periodically. You can only renew a non-expired TGT.

**Comment by ElectricVampire** [comment]
Once TGT near expiration (essentially EndTime property value), can I use Kerberos.NET to request new TGT from KDC or do I have to fetch new krb5cc file using API call?

**Comment by SteveSyfuhs** [comment]
I just looked at the code and we don't renew TGTs when using the file cache and it looks like we are tracking it with #285. Oops. Easy answer is 'no' then. Just request a new krb5cc file.

**Comment by ElectricVampire** [comment]
Thanks for confirmation.
So essentially for me, If I am near `EndTime` - I'll make an API call and fetch new krb5Cache file . `RenewTill` property doesn't hold any value in this particular use case as if TGT is expired cache file is invalid as there is no way to renew TGT.
