### ISSUE TITLE
Getting casting error when authenticating ticket

### ISSUE THREAD

**Issue by macsux** [SteveSyfuhs/Kerberos.NET#35]
I'm getting an exception when authenticating this ticket. 

System.InvalidCastException: Unable to cast object of type 'Kerberos.NET.Entities.NegTokenTarg' to type 'Kerberos.NET.Entities.ContextToken'.
   at Kerberos.NET.KerberosValidator.<Validate>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.KerberosAuthenticator.<Authenticate>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Kerberos.NET.KerberosAuthenticator.<Authenticate>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UserQuery.<Main>d__0.MoveNext() in C:\Users\astakhov\AppData\Local\Temp\LINQPad5\_joemrpwt\query_uelfxt.cs:line 37

SPN password is "New0rder"

Negotiate oYIG0DCCBsygAwoBAaKCBsMEgga/YIIGuwYJKoZIhvcSAQICAQBuggaqMIIGpqADAgEFoQMCAQ6iBwMFACAAAACjggTiYYIE3jCCBNqgAwIBBaEMGwpBTE1JUkVYLkRDoiEwH6ADAgECoRgwFhsESFRUUBsOYWQuYWxtaXJleC5jb22jggSgMIIEnKADAgEXoQMCAQKiggSOBIIEijZdM1Lqxe9ev+WykLJko9XhMPRl2/TxnuM3GOSfUUyEyheAj2mRgTwGfAkjMdYI44+gNLSVa+pIvAkJ9cbb0HVqRIgv7R4QAB0ftBtLpjdRpUjmBRbmZ4pjSbN9DHEWPxIqW3EYhbOOFSjgPXEVXieHS/UbGlBGamxYzHH+ngq/NvZqwZWwFLb/QFC32QKvbjYeKytDjF24czwm/e9316Uh81nUfQmhaUJmwRMEKvNgUyBRX555xkgx90kAlD6BC7QtCkRDmHtuG/vLr093CEE/KxjCt659DAj8rTtnUOlmY0EvhRfhgIXuAMG5UOl6e5fNnsd4/UHajcCBvlMX0h7tCSmXCZHIZj5MzEG6jLYj42kpgyQmo3zSoLKXfBR/L96QJtWbrmq4wcdQTHafWCjAtLmsE8birCco1p0VhU52ztbQD1dYGBcvJoh6NjaVIvazhrRCYOmJEZuVnZ32XCvaeEccamuIMQErxovqQ2+cLTLVgRzKExGxkXREEZu4oClE9BrjulwjeO89BNhlfmLxpDUuqF5CGdU/gp9FmlCMyLzlrTzm+i8+K5CX0/l6RL3xlHrh7DPwC9/1vNoaz2S3xp3w4KMeySXY+rQN2K9J2v3p1EBB/A08UaaVzF7/qukXYgaFUn2pEG7ywlulp0a097qxFT73flT9g99+33kgF1vh03JOEm1Pj2Au+e8M3P8SN0Ung7cPOIvLutj+l5SLLTDdxLC+QODF/SHlb/INNChbptf9qKMW3jMqGvhZLhatVFBWExAHTvCRfyYEdUZY3q0YTrSJNx//Vvmt5NHKHibxyrBVk/AyoAHhXO8OSx2WMnaZesEUmSKTWoL1zqeANG0opADK1++gX2KdcvqxL54d3zUCAOr/FRc0vdVciwkAOft4aq5+Hniy7VJlNIfZsBCx8JHW0GwuM1LEOOWgSg5AH/38lgXw1yGsazXcz6/9h+Z3/EDIUT2UryfmP0e6wt5saqs5zFXl+J/OUMn+ugbC0sOFTAHAZ6Lz5UTkXfSVkShq1a5g9YBJSoiDTdSIJTLTYBXd377bZs8PtIFGxtvzCwmXa9BXh1uRIc3vMm64Gh8cl5Iud2BGNCVOZGGYG9etGD6RP/oHxrMJI/EbBxZxmDEBP2slYTc1Kv27Cbtke52IjIxwjCrM9d+x7GERD6UUOzaeRFf1I1dYOWgXjhGkVhfvWPLNmEv9EsHrpG4PyM+xllNKJ5OKqMZefdDFmo6O4lQIIP8KfWD8ZWZjwNuyjk6DWJU80WJ5jeD6FmTnQTOt6mek3b/xOWqwM2igpKKcIg/bbCvPqYfaeDuBjydFKthbZIyFmxH4VNuCfl6hZ0WIaIAwaRoXsKIZ1i2PoM7BOxctZ51ZqoJ8dUx3klfpz9xKzumjiswhg/alOFcmXe8bZd7aeA8F5Vmqwynm9yvX9jY4bvYzH1e6GrF7aOWxwkqiH6GfjmHAq63jHenR9vNryViVHdGPe57kfpg5YqnFl0JaUIL9i3Q5mR6y+TnjSuHDD4egxeodbKwuoEubm0igLE/+VxekggGpMIIBpaADAgEXooIBnASCAZj6K4D8NqBiw9JmgFkf/NHPdwDBt+ukckoDOJCtEPlNeK6mqA9q1CA9vGmh2F7QaBpQcULTINDhzSjyjDACbUN9OHFBRf4prrRJIAG4zYfip1ZF6/CPDlyYe5+PYH+g+tjbd/hLcoYGHjDx71n9clkiSghIEDicwWRQ5Bqos8n7L7LNTAqqanXW58mJOdnTRjqVsb56BDm7ZsmSMwIuVnw0iE9aHLLbXcp12rVkgzcVFod9r2FydAUIjXX/Uyfdqpo5o7/zy3R4KFPllzdw56ljl+sYlZ3WiWMkCPWwBnTGB+9ymwWrGP0zDpw9tz7/Ds3ThQxO7EQutGUvKmNnmdw7/eaXTYJgraHlQhlGnL4/Tc1Q7HfTXj0PWr0/8V0GJ/dMkjfjth/khHFQHKMdD+V5+m8qe/THDCNE5cLgZVduy3/Ib6L8qgOfoMJiAvLyNnjKhAYHa0uNLXtVGsIajCxF1wij0M6wJ2RJaiWhC9BVfcDqpEPnhfSD1bN2JfpY1R8RnBy7aCDPKfTyjLOD/5BC6jPhX3cF4h8=

**Comment by SteveSyfuhs** [comment]
Caught this separately and committed it as part of 

https://github.com/SteveSyfuhs/Kerberos.NET/commit/42cd4a5d29ca122bc922464ff7f9c257c227ea92

You should see a new nuget package v2.7 in the next little while as the build completes.
