### ISSUE TITLE
[Question] save generated tickets in windows credential manager

### ISSUE THREAD

**Issue by acquleo** [SteveSyfuhs/Kerberos.NET#358]
We need to authenticate an user using kerberos from a workstation not in domain.
Given the authentication we would like to generate an SPN ticket for a TERMSRV\<target> service and start a remote desktop session to the target machine using the given credential.
I would like to know if is it possible to implement such scenario for example saving the credential on windows credential manager.

Thanks

**Comment by SteveSyfuhs** [comment]
This has nothing to do with Kerberos.NET. That's a Windows question.

**Comment by acquleo** [comment]
> This has nothing to do with Kerberos.NET. That's a Windows question.

Agree, I thought someone could help me.
I'll close the question
Thanks
