### ISSUE TITLE
ClaimIdentity cannot be mapped to legacy format 

### ISSUE THREAD

**Issue by macsux** [SteveSyfuhs/Kerberos.NET#36]
Currently, when Authenticator establishes ClaimsIdentity, it does so in the format of "user@REALM". For dealing with legacy scenarios, it would be useful to have access to principal in "DOMAIN\user" format. I propose either: a) an option for authenticator on how to establish the primary Name claim. b) adding additional claim into ClaimIdentity in the legacy format. c) a+b

**Comment by SteveSyfuhs** [comment]
The intent was to try and align it with what .NET does natively, which I don't think has this behavior. Domain\user is not really a correct format for Kerberos either, so I'm wondering how this could be exposed correctly. I do see the issue you have though.

One thing you can do in the meantime is override the method `AddUser` on the `KerberosAuthenticator` class to change how the claim is generated.

________________________________

**Comment by macsux** [comment]
Actually, the default behavior for WindowsIdentity.Name property is the
DOMAIN\user format.
https://docs.microsoft.com/en-us/dotnet/api/system.security.principal.windowsidentity.name?view=netframework-4.8


I'm specifically dealing with this compatibility issue when using your
library right now as the existing legacy code we're putting on the platform
expects it in the old school format when using IWA.

**Comment by SteveSyfuhs** [comment]
Gotcha. The old NetBIOS components should be available in the PAC so it should be easy enough to build up that value. Will need to work through how to handle this so it's compatible both ways, but I have some ideas.

________________________________

**Comment by SteveSyfuhs** [comment]
Thanks for providing the change. You rock! I've approved, merged, built, and it's in the process of uploading to nuget as we speak. Expect a nuget version of v2.7.0508.1.

https://github.com/SteveSyfuhs/Kerberos.NET/pull/37
