### ISSUE TITLE
issues with DNS resolution, UDP/TCP communication, or Kerberos configuration in the Linux environment

### ISSUE THREAD

**Issue by DanielMGoldberg** [SteveSyfuhs/Kerberos.NET#374]
I am using the kerberos.net NuGet package to generate a Kerberos token. The code works correctly on my Windows machine, but when I run the same code in a Linux container on OpenShift, I receive the following error:

One or more errors occurred. (cannot locate SRV record for x.corp) (KDC KRB_ERR_RESPONSE_TOO_BIG: response too big for udp; retry with TCP) (cannot locate a KDC proxy endpoint for x.corp)

To Reproduce
Create a Linux container on OpenShift.

Install the kerberos.net NuGet package.

Attempt to generate a Kerberos token using the following code:

// Example code that generates a Kerberos token
string keyTabFilePath = "myPath"
var krb5Config = new Krb5Config(); // settings some kdc configurations.

using(var client = new KerberosClient(krb5Config))
{
var keytab= new KeyTable(File.ReadAllBytes(keyTabFilePath));
var kerbCred = new KeytabCredential("myUser.corp", keytab);

await client.Authenticate(kerbCred);
var ticket = await client.GetServiceTicket("zzz/x.corp");
var token = Convert.ToBase64String(ticket.EncodingGssApi().ToArray());

HttpClientHandler handler = new HttpClientHandler()
{
UseDefaultCredentials = false
}
using(HttpClient client = new HttpClient(handler))
{
client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Negotiate", token);
HttpResponseMessage response = client.GetAsync(apiUrl).Result;
}

}

Expected Behavior
The Kerberos token should be generated successfully without any errors, as it does on Windows.

Additional Context
The same code works fine on a Windows environment.
The Linux container is running on OpenShift.
The error suggests potential issues with DNS resolution, UDP/TCP communication, or Kerberos configuration in the Linux environment.
Please let me know if any additional information or logs are needed to help troubleshoot this issue.

**Comment by LordXaosa** [comment]
Hi! How did you resolve your issue? Seems I have the same. Client auth on windows works fine, but in docker with same code on same machine I have this error (Cannot locate SRV record)
