### ISSUE TITLE
CacheInMemory = true , retrieve as file ?

### ISSUE THREAD

**Issue by DanielMGoldberg** [SteveSyfuhs/Kerberos.NET#376]
Hey,
I would like to know if it's possible to retrieve as a file the cache and save it as krbcache somewhere (i want to do it manually and not use CacheInMemory)

Thanks!

**Comment by SteveSyfuhs** [comment]
I don't understand what you're trying to do. Why would you want to mix these two scenarios?

**Comment by DanielMGoldberg** [comment]
> I don't understand what you're trying to do. Why would you want to mix these two scenarios?

I'm trying to send a krbcache file to another application via HTTPS protocol, So I'm trying to avoid storing the cache in my own app using the cacheInMemory.

**Comment by SteveSyfuhs** [comment]
Sure, you can just configure the cache property to use the file cache directly.

**Comment by DanielMGoldberg** [comment]
> Sure, you can just configure the cache property to use the file cache directly.

Thank you! :)
