### ISSUE TITLE
ASN1 decode error

### ISSUE THREAD

**Issue by DanielMGoldberg** [SteveSyfuhs/Kerberos.NET#377]
Describe the bug

When attempting to decode a Kerberos ticket encoded using ticket.EncodeGssApi().ToArray(), the KrbApReq.DecodeApplication method throws an ASN.1 parsing error: ASN1 corrupted data. Expected application-14 actual: constructed application-0. This indicates a mismatch in the expected ASN.1 structure for decoding the ticket.

To Reproduce

Here is a minimal code sample demonstrating the issue:

public class Program
{
    public static void Main()
    {
        // Sample code to generate a Kerberos ticket and encode it using GSS-API
        var client = new KerberosClient(); // Assuming client is correctly initialized
        var ticket = client.GetServiceTicket("HTTP/your-service");

        // Encode the ticket using GSS-API
        var encodedTicket = ticket.EncodeGssApi().ToArray();

        // Attempt to decode the ticket
        try
        {
            var decodedTicket = KrbApReq.DecodeApplication(encodedTicket);
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Error: {ex.Message}");
        }
    }
}
Expected behavior

I expect the KrbApReq.DecodeApplication method to successfully decode the GSS-API encoded Kerberos ticket and allow me to access the ticket details, including the principal name.

Additional context

The error message suggests that there is a discrepancy between the expected ASN.1 tag (application-14) and the actual tag found (constructed application-0). This could indicate that the encoding or structure of the ticket might not match the expected format for KrbApReq.DecodeApplication.
This issue might be related to the way the ticket is encoded or the specific implementation details of the EncodeGssApi method.

**Comment by SteveSyfuhs** [comment]
EncodeGssApi cannot round-trip through Decode. It's a GSS wrapper around the AP-REQ for NEGOTIATE messages. That's why it's a separate method and why the validator parses it separately. If you need it to round-trip then you have to use EncodeApplication.

**Comment by DanielMGoldberg** [comment]
@SteveSyfuhs Thank you so much! This library is really amazing :)
