### ISSUE TITLE
Extending LinuxCryptoPal?

### ISSUE THREAD

**Issue by jonnepmyra** [SteveSyfuhs/Kerberos.NET#379]
Hi,

First of all, thank you for providing a great library! We are currently working on adding container (Linux) compatibility to a large application platform that heavily relies on Windows authentication.

With the help of this library, we can now make outbound calls with Kerberos tokens and even authenticate incoming requests containing a Kerberos token, without requiring the container to be a member of the Active Directory (AD).

We understand from the documentation that RC4/MD4 encryption types are not supported in cross-platform scenarios. However, due to some unresolved issues in our environment (currently under investigation and out of scope here), our AD/KDC still issues tokens with `EType=RC4_HMAC_NT`.

Until the RC4_HMAC_NT issue is resolved in our environment, we would like to enable support for MD4/RC4 on Linux. Implementing an MD4 `IHashAlgorithm` seems straightforward (using bouncycastle):
```
public class Md4 : IHashAlgorithm
{
    public Md4() { }

    public void Dispose() { }

    public ReadOnlyMemory<byte> ComputeHash(ReadOnlySpan<byte> data)
    {
        var md4 = new MD4Digest();
        md4.BlockUpdate(data.ToArray(), 0, data.Length);
        var result = new byte[md4.GetDigestSize()];
        md4.DoFinal(result, 0);
        return result;
    }
}
```

Now, on to my question: It would be ideal if I could extend the `LinuxCryptoPal` class and override the following method:
`public override IHashAlgorithm Md4() => throw PlatformNotSupported("MD4");`

However, since `LinuxCryptoPal` is marked as `internal`, it is not extendable from outside the library.

Would it be possible to make LinuxCryptoPal public to facilitate extending it? Or is there an alternative approach to enable MD4/RC4 support in Linux?

Any guidance on this matter would be greatly appreciated.

Thank you for your time.

**Comment by SteveSyfuhs** [comment]
Will post a new nuget package shortly.
