### ISSUE TITLE
AES 256 Encryption type kerberos tickets

### ISSUE THREAD

**Issue by alosman24** [SteveSyfuhs/Kerberos.NET#38]
Hi, 

I am getting a kerberos ticket that is encrypted with a key using AES256, when i try to validate the ticket using your kerberos validator, i get invalid check-sum error.

`                    var kerberosValidator = new KerberosValidator(new KerberosKey("sampleKey")) { ValidateAfterDecrypt = ValidationActions.None };`
`                    var authenticator = new KerberosAuthenticator(kerberosValidator);`
`                    var identity = await authenticator.Authenticate(ticket);`

**Comment by SteveSyfuhs** [comment]
It likely can't derive the correct salt. I would recommend generating a keytab file in that case.

________________________________

**Comment by alosman24** [comment]
Ok thanks, i'll do that
