### ISSUE TITLE
Build failing -  AsnXml.targets(23, 5): [MSB4062] The "Microsoft.Build.Tasks.XslTransformation" task could not be loaded

### ISSUE THREAD

**Issue by macsux** [SteveSyfuhs/Kerberos.NET#48]
AsnXml.targets(23, 5): [MSB4062] The "Microsoft.Build.Tasks.XslTransformation" task could not be loaded from the assembly Microsoft.Build.Tasks.Core, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

**Comment by SteveSyfuhs** [comment]
At the moment it requires MSBuild because of that particular transform. The command line dotnet build will not work.

**Comment by macsux** [comment]
Can you please provide a tip on how to compile this? I'm having hard time to get msbuild to compile this, it's giving me C:\projects\Kerberos.NET\Kerberos.NET\Kerberos.NET.csproj.metaproj : warning MSB4078: The project file "Kerberos.NET\Kerberos.NET.c sproj" is not supported by MSBuild and cannot be built.

**Comment by SteveSyfuhs** [comment]
What version of MSBuild are you using? Are you running it from within the developer console?

Running this on a new install of Visual Studio works.


Developer Command Prompt for VS 2019 Preview > 
```cmd
cd c:\path\to\solution
msbuild Kerberos.NET.sln
```

```
Microsoft (R) Build Engine version 16.2.0-preview-19310-01+28ca8b4ea for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 8/13/2019 6:40:03 PM.
Project "C:\path\to\Kerberos.NET\Kerberos.NET.sln" on node 1 (default targets).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|Any CPU".
Project "C:\path\to\Kerberos.NET\Kerberos.NET.sln" (1) is building "C:\path\to\Kerberos.NET\Kerberos.NET\Kerberos.NET.csproj"
 (2) on node 1 (default targets).
_CheckForNETCoreSdkIsPreview:
C:\Program Files\dotnet\sdk\3.0.100-preview6-012264\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInfer
ence.targets(158,5): message NETSDK1057: You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-
preview [C:\path\to\Kerberos.NET\Kerberos.NET\Kerberos.NET.csproj]

.......... snip .........

Done Building Project "C:\path\to\Kerberos.NET\Kerberos.NET.sln" (default targets).


Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:14.90

```

**Comment by macsux** [comment]
That worked. Thanks

**Comment by macsux** [comment]
This worked. I'm still confused as to why "dotnet msbuild" wouldn't compile it though, the whole difference between dotnet and msbuild cli is not very obvious.

Another question, I noticed targeting for library is now netcoreapp vs netstandard. Is there a reason? We've been using it for legacy WCF work to accept and validate tickets without domain joining machines, which is now going to make it problematic...

**Comment by SteveSyfuhs** [comment]
There's a known issue in dotnet build where it just doesn't exist yet. You'll notice the last dozen or so major changes took on a new ASN encoder so if can do both creation and validation of tickets. This was forked from the corefx repo.

This necessarily required upgrading it to 2.1. I had to rebuild the project which took netcoreapp by default. I haven't tried standard yet. One of the reasons I haven't updated the nuget package yet.
