### ISSUE TITLE
Using the Base 64 string of ticket.EncodeNegotiate in Authorization header gets rejected by kerberos service.

### ISSUE THREAD

**Issue by CodingBeagle** [SteveSyfuhs/Kerberos.NET#70]
Hey,

This might just be me who does not have enough experience with the Kerberos protocol or the Kerberos.Net Nuget Package.

What I'm essentially attempting to do is call an API which required kerberos authentication.

Using Kerberos.NET, I have successfully gotten a Service Ticket from the authentication server for the SPN where the API is located.

However, after that it's not quite clear if I'm doing things correctly. What I want to do is put the ticket session key in the Authorization header, using the Negotiate scheme, when I send an HTTP request to the API. What I do right now is this:

`
var encodedNegotiateValue = Convert.ToBase64String(ticket.EncodeNegotiate().ToArray());

...
httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Negotiate", encodedNegotiateValue);

`

However, this does not work. Am I missing something essential, or using the API incorrectly? I tried to check out the End 2 End tests and saw that a test for negotiate was there. It also uses the Authenticator class. However, I'm not sure where this fits into the protocol, or how exactly to build up the Base 64 encoded negotiate string :)

**Comment by SteveSyfuhs** [comment]
How are you getting the ticket in this case? The code to convert it into a nego header looks correct.

**Comment by CodingBeagle** [comment]
@SteveSyfuhs Hey! thanks for the quick response! :) I will try out the EncodeGssApi() method tomorrow. I'll get back with a fuller code-snippet in case in doesn't work (I don't have the code at hand right now).

I'm essentially following the boiler-plate example of using the client first but authenticating and then calling GetServiceTicket(...). Right after the GetServiceTicket call, I then do what I showed in the original post. I **don't** use the Authenticator class with the keytables and all that. Is this something that I should be doing?

**Comment by SteveSyfuhs** [comment]
It looks like you're doing it correctly then. Just switch out the call to use `EncodeGssApi()` and you should be good to go. 

The `KerberosAuthenticator` class is used when you want to validate an incoming ticket, i.e. what the receiving server would do. The client doesn't normally have the secrets necessary to validate the ticket it sends to the server.

**Comment by CodingBeagle** [comment]
Hey @SteveSyfuhs , just wanted to say that using the _EncodeGssApi_ method call did the trick :) That gave us a valid Kerberos ticket.

The only real issue we've experienced since then has been that the TCP connection sometimes fails when calling _Authenticate_, however I suppose that can be due to any number of problems with the underlying network connection :) 

Thanks for the help!

**Comment by SteveSyfuhs** [comment]
Cool. What version of the library are you using? I fixed a TCP client bug sometime in the 3.0.* series.

If it's higher I'd love to see a network trace of that failure or a stack trace/exception detail of the failure.

________________________________

**Comment by CodingBeagle** [comment]
Hey @SteveSyfuhs , sorry about the late reply.

I'm using version **3.1.1**

I managed to re-create the exception. This is the info I got on it:

```
---- Kerberos.NET.Transport.KerberosTransportException : TCP Connect failed
-------- System.Net.Internals.SocketExceptionFactory+ExtendedSocketException : A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond **.***.***.***:88
   at *** in ***
   at *** in ***
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Kerberos.NET.Transport.KerberosTransportSelector.SendMessage[T](String domain, ReadOnlyMemory`1 encoded, CancellationToken cancellation)
   at Kerberos.NET.Client.KerberosClient.RequestTgt(KerberosCredential credential) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 310
   at Kerberos.NET.Client.KerberosClient.Authenticate(KerberosCredential credential) in D:\a\1\s\Kerberos.NET\Client\KerberosClient.cs:line 99
   at *** in ***
--- End of stack trace from previous location where exception was thrown ---
   at *** in ***
----- Inner Stack Trace -----
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(Object result, MultipleAddressConnectAsyncResult context)
   at System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.TcpClient.<>c.<ConnectAsync>b__28_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Kerberos.NET.Transport.TcpKerberosTransport.SendMessage[T](String domain, ReadOnlyMemory`1 encoded, CancellationToken cancellation) in D:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 43
```

Notice that I've left out some of the class and methods names from the codebase I'm working on with **'***'** but the left of the stack trace should be relevant to the Kerberos.Net framework.

**Comment by SteveSyfuhs** [comment]
Well that's certainly interesting. I wouldn't expect a socket timeout. Is the KDC Active Directory or something else?

Anything interesting going on in the KDC? E.g. Lots of group memberships, DC being on the other side of the moon, too much load, etc. AS-REQs don't normally time out. There's no good way to extend the timeout, but its already 30 seconds anyway.

________________________________

**Comment by CodingBeagle** [comment]
@SteveSyfuhs All I can say is that it's in a test environment, so there might definitely be some irregularities about it :) I will see how it goes with time.

Also, one last thing. Do you know when Linux will be supported. I see that when running it on a .Net Core application on a Linux distributation, the following error is received:

> DNS query is not supported on non-Win32 platforms yet

So far as I know, short of using whatever functionality the .Net Core HTTP Client has, there aren't any other authentication libraries cross-platform for .Net Core, is there?

**Comment by SteveSyfuhs** [comment]
Linux support is not quite as high a priority as some other things so I haven't devoted much time to it. There are ways around the above issue though, which is to just pass a known endpoint to the client `KerberosClient(overrideKdc: "10.1.1.1:88")`. This does mean you need to query for the DC yourself, which if you know the name and can resolve it's IP then it isn't horrible.

The other issue you'll run into is that the RC4 crypto system won't be available on Linux. It only supports AES. This shouldn't be an issue as AD supports AES, but you need to make sure it's configured correctly.

**Comment by CodingBeagle** [comment]
@SteveSyfuhs Hey man :) Using Net Core's Dns class to resolve IP addresses for the DC actually worked on Linux 👍 I'll try with that approach for now.

**Comment by SteveSyfuhs** [comment]
Cool. FWIW there are some important gotchas with DNS here, but they _probably_ won't affect you. Kerberos works by looking up the SRV record `_kerberos._tcp.[domain]`. This will almost always match A records of DCs, which will match the domain, but there are corner case scenarios where that doesn't apply.
