### ISSUE TITLE
Use Keytab file for Credentials

### ISSUE THREAD

**Issue by SyntakSoftware** [SteveSyfuhs/Kerberos.NET#71]
Hi All,

I was wondering if there was plans to be able to use a keytab file as means of authentication.

Something like:
... = new KerberosKeytabCredential("PrincipalNameHere", "./PathToKeytabFile", "realm");

Thanks much for the library.

**Comment by SteveSyfuhs** [comment]
I haven't added it yet, but PR's are welcome.

The keytab functionality is already present, and it produces `KerberosKey`’s. `KerberosCredential` is intended to be extended for the various credential types like passwords, certificates, etc. They also produce `KerberosKey`’s for the client to use.

I haven't tested this, but it would look something like this. 

```csharp
class KeytabCredential : KerberosCredential
{
    private readonly KeyTable keytab;

    public KeytabCredential(KeyTable keytab)
    {
        this.keytab = keytab;
    }

    public override KerberosKey CreateKey()
    {
        var principalName = new Entities.KrbPrincipalName() { Name = new[] { UserName } };

        if (!Salts?.Any() ?? false)
        {
            return keytab.GetKey(EncryptionType.NULL, principalName);
        }

        foreach (var salt in Salts)
        {
            var key = keytab.GetKey(salt.Key, principalName);

            if (key != null)
            {
                return key;
            }
        }

        return null;
    }
}
```
