### ISSUE TITLE
Change Active Directory password using Kerberos Change-Password protocol and .NET Core 3

### ISSUE THREAD

**Issue by Eng-Fouad** [SteveSyfuhs/Kerberos.NET#79]
By reading [Kerberos Change Password Protocol](https://tools.ietf.org/html/draft-ietf-cat-kerb-chg-password-02) and [Kerberos.NET Samples](https://github.com/SteveSyfuhs/Kerberos.NET/tree/master/Samples), I wrote the following code:

    using Kerberos.NET;
    using Kerberos.NET.Client;
    using Kerberos.NET.Credentials;
    using Kerberos.NET.Crypto;
    using Kerberos.NET.Entities;
    using System;
    using System.Linq;
    using System.Net.Sockets;
    using System.Text;
    using System.Threading.Tasks;
    
    namespace KerberosDemo
    {
        class Program
        {
            static async Task Main(string[] args)
            {
                string activeDirectoryServer = "10.12.34.56:88"; // kdc port
                string domain = "TEST.LOCAL";
                string username = "testuser@" + domain;
                string oldPassword = "123";
                string newPassword = "456";
    
                using var client = new KerberosClient(activeDirectoryServer);
                var kerbCred = new KerberosPasswordCredential(username, oldPassword, domain);
                await client.Authenticate(kerbCred);
                var serviceTicket = await client.GetServiceTicket("kadmin/changepw");
    
                var apReq = new KrbApReq
                {
                    Ticket = serviceTicket.Ticket,
                    Authenticator = KrbEncryptedData.Encrypt(Encoding.UTF8.GetBytes(newPassword).AsMemory(), kerbCred.CreateKey(), KeyUsage.ApReqAuthenticator),
                    ProtocolVersionNumber = 1
                };
    
                var tcp = client.Transports.FirstOrDefault(t => t.Protocol == ProtocolType.Tcp);
                await tcp.SendMessage<KrbApReq, KrbAsRep>(domain, apReq);
            }
        }
    }

I got the following exception at `await tcp.SendMessage<KrbApReq, KrbAsRep>(domain, apReq);`:

> Unhandled exception.
> System.Security.Cryptography.CryptographicException: ASN1 corrupted
> data.    at
> System.Security.Cryptography.Asn1.AsnReader.ReadTagAndLength(Nullable`1&
> contentsLength, Int32& bytesRead) in
> d:\a\1\s\Kerberos.NET\Asn1\Experimental\AsnReader.cs:line 305    at
> Kerberos.NET.Entities.KrbError.CanDecode(ReadOnlyMemory`1 encoded) in
> d:\a\1\s\Kerberos.NET\Entities\Krb\KrbError.cs:line 23    at
> Kerberos.NET.Transport.KerberosTransportBase.Decode[T](ReadOnlyMemory`1
> response) in
> d:\a\1\s\Kerberos.NET\Client\Transport\KerberosTransportBase.cs:line
> 41    at
> Kerberos.NET.Transport.TcpKerberosTransport.ReadResponse[T](NetworkStream
> stream, CancellationToken cancellation) in
> d:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 69
> at Kerberos.NET.Transport.TcpKerberosTransport.SendMessage[T](String
> domain, ReadOnlyMemory`1 encoded, CancellationToken cancellation) in
> d:\a\1\s\Kerberos.NET\Client\Transport\TcpKerberosTransport.cs:line 58
> at KerberosDemo.Program.Main(String[] args)    at
> KerberosDemo.Program.<Main>(String[] args)

Your help is appreciated. Thanks.

https://stackoverflow.com/questions/58670044/change-active-directory-password-using-kerberos-change-password-protocol-and-ne

**Comment by SteveSyfuhs** [comment]
There's a few things going on here. The message format doesn't appear to match what you're sending. You would need to build a new message that includes the length, ap-req, and krb-priv all in a single request.

The other thing is that it appears that you're sending the request to port 88 which is normal for all other messages, but changepw requires it go to 464.

________________________________
